// Static data for investigations — in a real app this would come from Supabase

export interface Investigation {
  id: string;
  title: string;
  slug: string;
  description: string;
  category: string;
  evidenceScore: number;
  year?: string;
  wikiTitle: string;
  imageUrl?: string;
}

export const featuredInvestigation: Investigation = {
  id: "area-51",
  title: "Area 51: What Really Happened?",
  slug: "area-51",
  description:
    "Decades of secrecy surrounding the Nevada test site have spawned countless theories. Declassified documents reveal a more complex truth — but many questions remain unanswered.",
  category: "Government",
  evidenceScore: 74,
  year: "1955",
  wikiTitle: "Area 51",
};

// ── Full investigation dataset ────────────────────────────────────────────
export const allInvestigations: Investigation[] = [
  // UFO
  {
    id: "uss-nimitz",
    title: "USS Nimitz UFO Encounter",
    slug: "uss-nimitz",
    description: "In November 2004, US Navy pilots encountered a white Tic-Tac shaped object off San Diego that outperformed every known aircraft. Cmdr. David Fravor's testimony and gun-camera footage remain the most credible military UAP evidence on record.",
    category: "UFO",
    evidenceScore: 92,
    year: "2004",
    wikiTitle: "2004 USS Nimitz UFO incident",
  },
  {
    id: "belgium-ufo-wave",
    title: "Belgian UFO Wave",
    slug: "belgium-ufo-wave",
    description: "Between 1989 and 1990, over 13,500 people — including police and military — reported large triangular craft over Belgium. Two F-16s gave chase; the object performed manoeuvres no known aircraft could survive.",
    category: "UFO",
    evidenceScore: 71,
    year: "1989",
    wikiTitle: "Belgian UFO wave",
  },
  {
    id: "travis-walton",
    title: "Travis Walton Abduction",
    slug: "travis-walton",
    description: "On November 5, 1975, logger Travis Walton vanished in front of six witnesses after approaching a glowing disc in an Arizona forest. He reappeared five days later with fragmented memories of an alien craft. All seven men passed polygraph tests.",
    category: "UFO",
    evidenceScore: 44,
    year: "1975",
    wikiTitle: "Travis Walton incident",
  },
  {
    id: "uss-roosevelt",
    title: "USS Roosevelt 'Gimbal' Object",
    slug: "uss-roosevelt",
    description: "In 2015, pilots aboard USS Theodore Roosevelt filmed the now-famous 'Gimbal' UAP rotating against the wind at high altitude. The Defense Intelligence Agency confirmed the footage was real and unclassified.",
    category: "UFO",
    evidenceScore: 88,
    year: "2015",
    wikiTitle: "Pentagon UFO videos",
  },
  {
    id: "roswell",
    title: "The Roswell Incident",
    slug: "roswell",
    description: "A 1947 crash in New Mexico that changed how the world thinks about UFOs and government secrecy.",
    category: "UFO",
    evidenceScore: 68,
    year: "1947",
    wikiTitle: "Roswell UFO incident",
  },
  {
    id: "phoenix-lights",
    title: "The Phoenix Lights",
    slug: "phoenix-lights",
    description: "On March 13, 1997, thousands of Arizona residents reported a massive V-shaped formation of lights gliding silently across the night sky. The US Air Force offered an explanation — few believed it.",
    category: "UFO",
    evidenceScore: 61,
    year: "1997",
    wikiTitle: "Phoenix Lights",
  },
  {
    id: "rendlesham",
    title: "Rendlesham Forest Incident",
    slug: "rendlesham-forest",
    description: "Described as Britain's Roswell, US military personnel at RAF Woodbridge reported landing lights, a metallic craft, and radiation readings that have never been fully explained.",
    category: "UFO",
    evidenceScore: 55,
    year: "1980",
    wikiTitle: "Rendlesham Forest incident",
  },
  {
    id: "bob-lazar",
    title: "Bob Lazar: Area S-4 Whistleblower",
    slug: "bob-lazar",
    description: "Bob Lazar claims he worked on reverse-engineering alien propulsion systems at a secret facility near Area 51. His credentials were disputed — until some were quietly confirmed.",
    category: "UFO",
    evidenceScore: 38,
    year: "1989",
    wikiTitle: "Bob Lazar",
  },
  {
    id: "pentagon-uap",
    title: "Pentagon UAP Disclosure",
    slug: "pentagon-uap",
    description: "The US military officially released videos of Unidentified Aerial Phenomena in 2020 — the Tic Tac, Gimbal, and Go Fast videos. Congress continues to hold closed-door hearings.",
    category: "UFO",
    evidenceScore: 79,
    year: "2017",
    wikiTitle: "Pentagon UFO videos",
  },
  // Government
  {
    id: "operation-northwoods",
    title: "Operation Northwoods",
    slug: "operation-northwoods",
    description: "In 1962, the Joint Chiefs of Staff signed off on a plan to stage false-flag terrorist attacks on American citizens — including shooting down a civilian airliner — to justify an invasion of Cuba. President Kennedy rejected it.",
    category: "Government",
    evidenceScore: 99,
    year: "1962",
    wikiTitle: "Operation Northwoods",
  },
  {
    id: "prism",
    title: "PRISM: NSA Mass Surveillance",
    slug: "nsa-prism",
    description: "In 2013, Edward Snowden leaked classified documents revealing the NSA had built a secret system to collect internet communications from nine major US tech companies — Microsoft, Google, Apple, Facebook and others — without individual warrants.",
    category: "Government",
    evidenceScore: 100,
    year: "2013",
    wikiTitle: "PRISM",
  },
  {
    id: "cia-heart-attack-gun",
    title: "CIA Assassination Weapons",
    slug: "cia-assassination-weapons",
    description: "In 1975, CIA Director William Colby revealed to the Church Committee that the agency had developed an untraceable dart gun capable of inducing a fatal heart attack. The dart dissolved on impact, leaving no trace of poison in autopsy.",
    category: "Government",
    evidenceScore: 97,
    year: "1975",
    wikiTitle: "Heart attack gun",
  },
  {
    id: "project-artichoke",
    title: "Project ARTICHOKE",
    slug: "project-artichoke",
    description: "Before MK Ultra, the CIA's Project ARTICHOKE explored whether a person could be compelled to carry out an assassination then forget they had done it. Declassified documents confirm experiments on prisoners and unwitting soldiers.",
    category: "Government",
    evidenceScore: 94,
    year: "1951",
    wikiTitle: "Project ARTICHOKE",
  },
  {
    id: "area-51",
    title: "Area 51: What Really Happened?",
    slug: "area-51",
    description: "Decades of secrecy surrounding the Nevada test site have spawned countless theories. Declassified documents reveal a more complex truth — but many questions remain unanswered.",
    category: "Government",
    evidenceScore: 74,
    year: "1955",
    wikiTitle: "Area 51",
  },
  {
    id: "mkultra",
    title: "MK Ultra",
    slug: "mk-ultra",
    description: "The CIA's secret mind control program that tested LSD and psychological torture on unwitting subjects for over a decade.",
    category: "Government",
    evidenceScore: 91,
    year: "1953",
    wikiTitle: "Project MKUltra",
  },
  {
    id: "philadelphia-experiment",
    title: "The Philadelphia Experiment",
    slug: "philadelphia-experiment",
    description: "Did the US Navy render a warship invisible and teleport it in 1943? Declassified records raise more questions than answers.",
    category: "Government",
    evidenceScore: 22,
    year: "1943",
    wikiTitle: "Philadelphia Experiment",
  },
  {
    id: "jfk",
    title: "JFK Assassination Files",
    slug: "jfk-assassination",
    description: "Newly released CIA documents add fresh layers to one of history's most scrutinised events. Key records remain classified until 2039.",
    category: "Government",
    evidenceScore: 71,
    year: "1963",
    wikiTitle: "Assassination of John F. Kennedy",
  },
  {
    id: "operation-paperclip",
    title: "Operation Paperclip",
    slug: "operation-paperclip",
    description: "After World War II, the US secretly recruited over 1,600 Nazi scientists — including Wernher von Braun — to work on military and space programs. Most were given falsified records.",
    category: "Government",
    evidenceScore: 96,
    year: "1945",
    wikiTitle: "Operation Paperclip",
  },
  {
    id: "cointelpro",
    title: "COINTELPRO",
    slug: "cointelpro",
    description: "Declassified FBI documents confirmed a decade-long covert program to surveil, infiltrate, and disrupt civil rights groups, anti-war activists, and political organisations.",
    category: "Government",
    evidenceScore: 98,
    year: "1956",
    wikiTitle: "COINTELPRO",
  },
  {
    id: "tuskegee",
    title: "Tuskegee Syphilis Study",
    slug: "tuskegee-study",
    description: "For 40 years, the US Public Health Service deliberately withheld treatment from 399 Black men with syphilis to study disease progression. The experiment ended only after a whistleblower came forward.",
    category: "Government",
    evidenceScore: 99,
    year: "1932",
    wikiTitle: "Tuskegee Syphilis Study",
  },
  // Unexplained
  {
    id: "oak-island",
    title: "Oak Island Money Pit",
    slug: "oak-island",
    description: "Since 1795, treasure hunters have been digging on a small Nova Scotia island after a teenager found a circular depression in the ground. The pit floods automatically at 33 feet. Six people have died trying to reach the bottom. Nothing definitive has ever been found.",
    category: "Unexplained",
    evidenceScore: 41,
    year: "1795",
    wikiTitle: "Oak Island",
  },
  {
    id: "d-b-cooper-briefcase",
    title: "The Zodiac Cipher",
    slug: "zodiac-cipher",
    description: "The Zodiac Killer sent four encrypted messages to police and newspapers between 1969 and 1974. Three remain unsolved. The killer was never caught. The 340-character cipher went unsolved for 51 years until a team of amateur cryptologists cracked it in 2020.",
    category: "Unexplained",
    evidenceScore: 64,
    year: "1969",
    wikiTitle: "Zodiac Killer",
  },
  {
    id: "patomskiy-crater",
    title: "Patomskiy Crater",
    slug: "patomskiy-crater",
    description: "A massive conical mound of shattered limestone in the remote Siberian taiga, 40 metres high and 160 metres across. Local Yakuts call it the Eagle's Nest and refuse to go near it. Animals avoid it. The origin is unknown.",
    category: "Unexplained",
    evidenceScore: 53,
    year: "1949",
    wikiTitle: "Patomskiy crater",
  },
  {
    id: "spontaneous-combustion",
    title: "Spontaneous Human Combustion",
    slug: "spontaneous-human-combustion",
    description: "Hundreds of documented cases describe human bodies reduced to ash — while surrounding furniture remains intact. The 'wick effect' hypothesis is disputed. Some cases leave no forensic explanation.",
    category: "Unexplained",
    evidenceScore: 36,
    wikiTitle: "Spontaneous human combustion",
  },
  {
    id: "dyatlov",
    title: "Dyatlov Pass Incident",
    slug: "dyatlov-pass",
    description: "Nine experienced hikers died mysteriously in the Ural Mountains. The cause remains disputed despite a 2019 Russian government investigation.",
    category: "Unexplained",
    evidenceScore: 55,
    year: "1959",
    wikiTitle: "Dyatlov Pass incident",
  },
  {
    id: "bermuda-triangle",
    title: "Bermuda Triangle",
    slug: "bermuda-triangle",
    description: "Recent oceanographic surveys offer new explanations for the mysterious disappearances in this stretch of the Atlantic.",
    category: "Unexplained",
    evidenceScore: 45,
    wikiTitle: "Bermuda Triangle",
  },
  {
    id: "havana-syndrome",
    title: "Havana Syndrome",
    slug: "havana-syndrome",
    description: "Since 2016, hundreds of US diplomats and intelligence officers have reported debilitating neurological symptoms. The CIA concluded most cases have no foreign cause — but 24 remain unexplained.",
    category: "Unexplained",
    evidenceScore: 62,
    year: "2016",
    wikiTitle: "Havana syndrome",
  },
  {
    id: "taos-hum",
    title: "The Taos Hum",
    slug: "taos-hum",
    description: "Since the early 1990s, residents of Taos, New Mexico have reported a persistent low-frequency hum audible to only 2% of the population. Multiple government investigations failed to identify the source.",
    category: "Unexplained",
    evidenceScore: 58,
    year: "1991",
    wikiTitle: "Taos Hum",
  },
  // Ancient Mysteries
  {
    id: "sacsayhuaman",
    title: "Sacsayhuamán Fortress",
    slug: "sacsayhuaman",
    description: "The Inca fortress above Cusco is built from stones weighing up to 125 tonnes, fitted together without mortar so precisely that a razor blade cannot pass between them. Modern engineers cannot explain how they were transported or shaped with only stone tools.",
    category: "Ancient Mysteries",
    evidenceScore: 73,
    year: "1438",
    wikiTitle: "Sacsayhuamán",
  },
  {
    id: "antikythera",
    title: "The Antikythera Mechanism",
    slug: "antikythera-mechanism",
    description: "A 2,000-year-old bronze device recovered from a Greek shipwreck that could calculate the positions of the sun, moon and planets with extraordinary accuracy. The technology it represents wouldn't reappear in Europe for another 1,400 years.",
    category: "Ancient Mysteries",
    evidenceScore: 95,
    year: "100 BCE",
    wikiTitle: "Antikythera mechanism",
  },
  {
    id: "baalbek",
    title: "Baalbek Megaliths",
    slug: "baalbek-megaliths",
    description: "The Roman temple complex at Baalbek, Lebanon sits on a platform of stone blocks weighing over 800 tonnes each — among the heaviest objects ever moved by humans. No ancient crane or machine capable of lifting them has ever been identified.",
    category: "Ancient Mysteries",
    evidenceScore: 67,
    year: "50 BCE",
    wikiTitle: "Baalbek",
  },
  {
    id: "piri-reis",
    title: "Piri Reis Map",
    slug: "piri-reis-map",
    description: "A 1513 Ottoman map that appears to accurately depict the coastline of Antarctica — 300 years before the continent was officially discovered. The map's source charts are unknown. Modern researchers continue to debate its accuracy and implications.",
    category: "Ancient Mysteries",
    evidenceScore: 49,
    year: "1513",
    wikiTitle: "Piri Reis map",
  },
  {
    id: "atlantis",
    title: "Atlantis: Lost Civilization",
    slug: "atlantis",
    description: "Plato described an advanced civilization swallowed by the sea. Archaeologists still debate whether this was allegory, myth, or memory.",
    category: "Ancient Mysteries",
    evidenceScore: 28,
    year: "360 BCE",
    wikiTitle: "Atlantis",
  },
  {
    id: "nazca-lines",
    title: "Nazca Lines Mystery",
    slug: "nazca-lines",
    description: "Ancient geoglyphs in Peru so large they can only be appreciated from the sky. Who made them, and why?",
    category: "Ancient Mysteries",
    evidenceScore: 62,
    year: "500 BCE",
    wikiTitle: "Nazca Lines",
  },
  {
    id: "stonehenge",
    title: "Stonehenge",
    slug: "stonehenge",
    description: "The massive stones were transported hundreds of miles from Wales without wheels or iron tools. New research suggests the site was simultaneously a burial ground, healing centre, and astronomical calendar.",
    category: "Ancient Mysteries",
    evidenceScore: 71,
    year: "3000 BCE",
    wikiTitle: "Stonehenge",
  },
  {
    id: "great-pyramid",
    title: "Great Pyramid of Giza",
    slug: "great-pyramid",
    description: "Constructed with such precision that a human hair cannot be inserted between the casing stones, the Great Pyramid still defies our understanding of ancient engineering capabilities.",
    category: "Ancient Mysteries",
    evidenceScore: 75,
    year: "2560 BCE",
    wikiTitle: "Great Pyramid of Giza",
  },
  {
    id: "gobekli-tepe",
    title: "Göbekli Tepe",
    slug: "gobekli-tepe",
    description: "Built 11,500 years ago by hunter-gatherers with no known writing, metal tools, or agriculture — 6,000 years before Stonehenge. It rewrites everything we thought we knew about civilisation.",
    category: "Ancient Mysteries",
    evidenceScore: 88,
    year: "9600 BCE",
    wikiTitle: "Göbekli Tepe",
  },
  {
    id: "easter-island",
    title: "Easter Island Statues",
    slug: "easter-island",
    description: "Nearly 900 massive stone statues were carved and transported across a remote Pacific island by a civilisation that then seemingly collapsed — raising questions about environmental overextension.",
    category: "Ancient Mysteries",
    evidenceScore: 69,
    year: "1250 CE",
    wikiTitle: "Easter Island",
  },
  // Historical
  {
    id: "amelia-earhart",
    title: "Amelia Earhart's Disappearance",
    slug: "amelia-earhart",
    description: "On July 2, 1937, pioneer aviator Amelia Earhart and navigator Fred Noonan vanished over the Pacific on the final leg of a round-the-world flight. New forensic analysis of a 1940 skeleton and radio transmissions suggests they survived the crash — for a while.",
    category: "Historical",
    evidenceScore: 61,
    year: "1937",
    wikiTitle: "Amelia Earhart",
  },
  {
    id: "skripals",
    title: "Salisbury Novichok Poisonings",
    slug: "salisbury-novichok",
    description: "In 2018, former Russian double-agent Sergei Skripal and his daughter were poisoned with a military-grade nerve agent on a British street. The UK government attributed the attack to Russian intelligence. Moscow denied involvement. One British civilian died.",
    category: "Historical",
    evidenceScore: 91,
    year: "2018",
    wikiTitle: "Poisoning of Sergei and Yulia Skripal",
  },
  {
    id: "princes-tower",
    title: "The Princes in the Tower",
    slug: "princes-in-the-tower",
    description: "In 1483, King Edward IV's two young sons were placed in the Tower of London by their uncle — and vanished from history. Richard III was crowned shortly after. No bodies were officially identified for centuries. New DNA analysis is ongoing.",
    category: "Historical",
    evidenceScore: 47,
    year: "1483",
    wikiTitle: "Princes in the Tower",
  },
  {
    id: "sodder-children",
    title: "The Sodder Children Disappearance",
    slug: "sodder-children",
    description: "On Christmas Eve 1945, a fire destroyed the Sodder family home in West Virginia. Five of the ten children were never found — no remains, no trace. The family believed they escaped and were kidnapped. The case was never solved.",
    category: "Historical",
    evidenceScore: 55,
    year: "1945",
    wikiTitle: "Sodder children",
  },
  {
    id: "voynich",
    title: "The Voynich Manuscript",
    slug: "voynich-manuscript",
    description: "An undeciphered illustrated book written in an unknown script, possibly from the 15th century. Every major cryptanalyst and codebreaker has failed to crack it.",
    category: "Historical",
    evidenceScore: 38,
    wikiTitle: "Voynich manuscript",
  },
  {
    id: "mary-celeste",
    title: "Mary Celeste",
    slug: "mary-celeste",
    description: "In 1872 the brigantine Mary Celeste was found adrift in the Atlantic, perfectly seaworthy, with food on the table — but completely abandoned. The crew of ten was never found.",
    category: "Historical",
    evidenceScore: 52,
    year: "1872",
    wikiTitle: "Mary Celeste",
  },
  {
    id: "roanoke",
    title: "Lost Colony of Roanoke",
    slug: "roanoke-colony",
    description: "In 1590, the governor of Roanoke Island returned from England to find the colony of 115 men, women, and children had completely vanished, leaving only the word CROATOAN carved into a post.",
    category: "Historical",
    evidenceScore: 60,
    year: "1590",
    wikiTitle: "Roanoke Colony",
  },
  {
    id: "jack-the-ripper",
    title: "Jack the Ripper",
    slug: "jack-the-ripper",
    description: "The unidentified serial killer who murdered at least five women in Whitechapel in 1888 has inspired over 100 named suspects and generated more theories than any cold case in history.",
    category: "Historical",
    evidenceScore: 44,
    year: "1888",
    wikiTitle: "Jack the Ripper",
  },
  {
    id: "db-cooper",
    title: "D.B. Cooper",
    slug: "db-cooper",
    description: "In 1971, a man hijacked a Northwest Orient flight, extorted $200,000 in ransom, and parachuted into a remote Pacific Northwest wilderness — never to be seen again. The only unsolved air piracy case in US history.",
    category: "Historical",
    evidenceScore: 66,
    year: "1971",
    wikiTitle: "D. B. Cooper",
  },
  // Science
  {
    id: "fast-radio-bursts",
    title: "Fast Radio Bursts",
    slug: "fast-radio-bursts",
    description: "Millisecond-long pulses of radio energy from deep space so powerful they release more energy than the sun emits in a year. Some repeat on precise schedules. Their origin — natural or otherwise — is one of astrophysics' biggest open questions.",
    category: "Science",
    evidenceScore: 78,
    year: "2007",
    wikiTitle: "Fast radio burst",
  },
  {
    id: "fermi-paradox",
    title: "The Fermi Paradox",
    slug: "fermi-paradox",
    description: "If the universe contains billions of Earth-like planets and life arose easily, where is everyone? The absence of detectable alien civilisations contradicts statistical probability. Every proposed solution raises deeper questions.",
    category: "Science",
    evidenceScore: 81,
    year: "1950",
    wikiTitle: "Fermi paradox",
  },
  {
    id: "oumuamua",
    title: "'Oumuamua: Visitor from Beyond",
    slug: "oumuamua",
    description: "The first interstellar object detected passing through our solar system accelerated away from the sun without any observable outgassing — behaviour no comet or asteroid should exhibit. Harvard astronomer Avi Loeb argued it could be artificial in origin.",
    category: "Science",
    evidenceScore: 63,
    year: "2017",
    wikiTitle: "ʻOumuamua",
  },
  {
    id: "orch-or",
    title: "Quantum Consciousness",
    slug: "quantum-consciousness",
    description: "Physicists Penrose and Hameroff proposed that consciousness arises from quantum computations in neural microtubules. If correct, it would imply that the mind cannot be fully replicated in silicon — and that reality depends on the observer.",
    category: "Science",
    evidenceScore: 42,
    year: "1994",
    wikiTitle: "Orchestrated objective reduction",
  },
  {
    id: "tunguska",
    title: "Tunguska Event",
    slug: "tunguska",
    description: "The largest impact event in recorded history. In 1908, something flattened 2,000 km² of Siberian forest without leaving a crater.",
    category: "Science",
    evidenceScore: 82,
    year: "1908",
    wikiTitle: "Tunguska event",
  },
  {
    id: "wow-signal",
    title: "The Wow! Signal",
    slug: "wow-signal",
    description: "On August 15, 1977, a radio telescope at Ohio State University detected a signal so powerful that astronomer Jerry Ehman scrawled 'Wow!' in the margin. It lasted 72 seconds and has never been detected again.",
    category: "Science",
    evidenceScore: 72,
    year: "1977",
    wikiTitle: "Wow! signal",
  },
  {
    id: "dark-matter",
    title: "Dark Matter",
    slug: "dark-matter",
    description: "Approximately 27% of the universe is made of a substance that emits no light, cannot be seen, and has never been directly detected — yet its gravitational effects shape every galaxy.",
    category: "Science",
    evidenceScore: 85,
    year: "1933",
    wikiTitle: "Dark matter",
  },
  {
    id: "ball-lightning",
    title: "Ball Lightning",
    slug: "ball-lightning",
    description: "Thousands of eyewitnesses over centuries have reported glowing orbs of light that move against the wind, pass through glass, and vanish suddenly. Science has no consensus explanation.",
    category: "Science",
    evidenceScore: 59,
    wikiTitle: "Ball lightning",
  },
  // Urban Legends
  {
    id: "black-eyed-children",
    title: "Black-Eyed Children",
    slug: "black-eyed-children",
    description: "Since the 1980s, people across the world have reported encounters with child-sized figures with completely black eyes who ask to be let inside. The reports are strikingly consistent — and deeply unsettling. No confirmed origin exists.",
    category: "Urban Legends",
    evidenceScore: 8,
    year: "1988",
    wikiTitle: "Black-eyed children",
  },
  {
    id: "spring-heeled-jack",
    title: "Spring-Heeled Jack",
    slug: "spring-heeled-jack",
    description: "For over 60 years from 1837, witnesses across Victorian Britain reported a terrifying figure that leaped over rooftops, breathed blue flame, and attacked women. The sightings began in London and spread across the country. No explanation was ever found.",
    category: "Urban Legends",
    evidenceScore: 14,
    year: "1837",
    wikiTitle: "Spring-heeled Jack",
  },
  {
    id: "slender-man",
    title: "The Slender Man Origin",
    slug: "slender-man",
    description: "Created as an internet meme in 2009, Slender Man inspired two 12-year-old girls to attempt murder in 2014. Researchers now study how a fictional entity became a real-world threat — and what it reveals about modern mythology and viral panic.",
    category: "Urban Legends",
    evidenceScore: 88,
    year: "2009",
    wikiTitle: "Slender Man",
  },
  {
    id: "poltergeist-enfield",
    title: "The Enfield Poltergeist",
    slug: "enfield-poltergeist",
    description: "From 1977 to 1978, a north London council house was the scene of furniture movements, knocking, levitation and a child speaking in a gruff adult voice. The case was investigated by the Society for Psychical Research and witnessed by journalists and police.",
    category: "Urban Legends",
    evidenceScore: 29,
    year: "1977",
    wikiTitle: "Enfield poltergeist",
  },
  {
    id: "bigfoot",
    title: "Bigfoot / Sasquatch",
    slug: "bigfoot",
    description: "The legend of a large bipedal hominid in North American forests has persisted for centuries. Native American traditions predate European contact. The 1967 Patterson–Gimlin film remains the most analyzed piece of evidence.",
    category: "Urban Legends",
    evidenceScore: 18,
    wikiTitle: "Bigfoot",
  },
  {
    id: "loch-ness",
    title: "Loch Ness Monster",
    slug: "loch-ness-monster",
    description: "Since the 1930s, hundreds of alleged sightings of a large creature in Scotland's Loch Ness have driven expeditions, sonar surveys, and DNA analysis. A 2023 environmental DNA study found no evidence of a large reptile.",
    category: "Urban Legends",
    evidenceScore: 12,
    year: "1933",
    wikiTitle: "Loch Ness Monster",
  },
  {
    id: "mothman",
    title: "The Mothman",
    slug: "mothman",
    description: "Between November 1966 and December 1967, over 100 residents of Point Pleasant, West Virginia reported a winged humanoid creature. The sightings coincided with the Silver Bridge collapse, killing 46.",
    category: "Urban Legends",
    evidenceScore: 25,
    year: "1966",
    wikiTitle: "Mothman",
  },
  {
    id: "men-in-black",
    title: "Men in Black",
    slug: "men-in-black",
    description: "Since the 1950s, UFO witnesses have reported visits from strange men in black suits who claim to be government agents and warn them to stay silent. The reports are eerily consistent across decades and continents.",
    category: "Urban Legends",
    evidenceScore: 21,
    year: "1947",
    wikiTitle: "Men in black (conspiracy theory)",
  },
  {
    id: "skinwalker-ranch",
    title: "Skinwalker Ranch",
    slug: "skinwalker-ranch",
    description: "A 512-acre Utah property with a 200-year history of paranormal activity: UFO sightings, cattle mutilations, poltergeist phenomena, and electromagnetic anomalies now under a Pentagon-linked investigation.",
    category: "Urban Legends",
    evidenceScore: 31,
    wikiTitle: "Skinwalker Ranch",
  },
  // Debunked
  {
    id: "paul-mccartney-dead",
    title: "Paul McCartney Is Dead",
    slug: "paul-mccartney-dead",
    description: "Since 1966, a persistent theory holds that the real Paul McCartney died in a car crash and was replaced by a lookalike named William Campbell. Believers cite reversed audio, album artwork and song lyrics as clues. Paul McCartney continues to sell out stadiums.",
    category: "Debunked",
    evidenceScore: 2,
    year: "1966",
    wikiTitle: "Paul is dead",
  },
  {
    id: "pyramids-aliens",
    title: "Pyramids Built by Aliens",
    slug: "pyramids-built-by-aliens",
    description: "Archaeologists have found workers' villages, payroll records, tools, graffiti and skeletal remains of pyramid builders. We know who built them, how, and roughly why. The 'aliens built the pyramids' theory erases the extraordinary achievement of thousands of skilled Egyptian workers.",
    category: "Debunked",
    evidenceScore: 2,
    year: "2560 BCE",
    wikiTitle: "Egyptian pyramids",
  },
  {
    id: "moon-landing-hoax",
    title: "Moon Landing Conspiracy",
    slug: "moon-landing-hoax",
    description: "The claim that NASA faked the 1969 Apollo landings has been independently refuted by multiple space agencies, hundreds of thousands of engineers, and retroreflectors still bouncing laser signals from the lunar surface today.",
    category: "Debunked",
    evidenceScore: 3,
    year: "1969",
    wikiTitle: "Moon landing conspiracy theories",
  },
  {
    id: "flat-earth",
    title: "Flat Earth Theory",
    slug: "flat-earth",
    description: "The claim that Earth is a flat disc contradicts GPS, satellite imagery, the physics of gravity, and the observations of every space agency — as well as simple experiments anyone can perform at home.",
    category: "Debunked",
    evidenceScore: 1,
    wikiTitle: "Flat Earth",
  },
  {
    id: "chemtrails",
    title: "Chemtrail Conspiracy",
    slug: "chemtrails",
    description: "The claim that aircraft contrails are chemical agents deliberately sprayed for population control. Atmospheric scientists have repeatedly explained contrail formation physics, and 77 of 77 surveyed experts dismissed the theory.",
    category: "Debunked",
    evidenceScore: 2,
    year: "1990s",
    wikiTitle: "Chemtrail conspiracy theory",
  },
  {
    id: "crop-circles",
    title: "Crop Circles: Alien Messages?",
    slug: "crop-circles",
    description: "From 1991, Doug Bower and Dave Chorley publicly demonstrated they had created hundreds of English crop circles with planks and rope. Despite this, new formations are still widely attributed to extraterrestrial origin.",
    category: "Debunked",
    evidenceScore: 5,
    year: "1978",
    wikiTitle: "Crop circle",
  },
];

// ── Curated subsets for the For You feed ─────────────────────────────────────
export const trendingInvestigations: Investigation[] = allInvestigations.filter((i) =>
  ["roswell", "mkultra", "dyatlov", "nazca-lines", "gobekli-tepe", "pentagon-uap"].includes(i.id)
);

export const latestInvestigations: Investigation[] = allInvestigations.filter((i) =>
  ["havana-syndrome", "wow-signal", "skinwalker-ranch", "roanoke"].includes(i.id)
);

export const timelineEvents = [
  { year: "1483", title: "Princes in the Tower", description: "Edward IV's heirs vanish from the Tower of London under Richard III's watch", category: "Historical" },
  { year: "1590", title: "Roanoke Colony", description: "115 colonists disappear. Only the word CROATOAN is left behind", category: "Historical" },
  { year: "1888", title: "Jack the Ripper", description: "Five Whitechapel murders. The killer is never identified", category: "Historical" },
  { year: "1908", title: "Tunguska Event", description: "Something flattens 2,000 km² of Siberian forest — no crater found", category: "Science" },
  { year: "1932", title: "Tuskegee Begins", description: "US government withholds syphilis treatment from 399 Black men for four decades", category: "Government" },
  { year: "1943", title: "MK Ultra Seeds", description: "Operation Paperclip recruits Nazi scientists for US mind-control research", category: "Government" },
  { year: "1947", title: "Roswell Incident", description: "Army announces 'flying disc' recovered — then retracts. Story buried for 30 years", category: "UFO" },
  { year: "1950", title: "Fermi Paradox", description: "Enrico Fermi asks: if the universe is full of life, where is everybody?", category: "Science" },
  { year: "1953", title: "MK Ultra Authorised", description: "CIA Director Dulles signs off on 150+ sub-projects in illegal mind control", category: "Government" },
  { year: "1959", title: "Dyatlov Pass", description: "Nine hikers found dead. Soviet investigators blame 'unknown compelling force'", category: "Unexplained" },
  { year: "1963", title: "JFK Assassinated", description: "Kennedy killed in Dallas. Oswald shot two days later. Files sealed for decades", category: "Government" },
  { year: "1977", title: "The Wow! Signal", description: "Ohio State telescope receives a 72-second broadcast from deep space, never heard again", category: "Science" },
  { year: "1980", title: "Rendlesham Forest", description: "US military personnel encounter a craft in a Suffolk forest. Radiation confirmed", category: "UFO" },
  { year: "1989", title: "Belgian UFO Wave", description: "13,500 witnesses report silent triangular craft. F-16s scrambled, nothing intercepted", category: "UFO" },
  { year: "2004", title: "USS Nimitz Encounter", description: "Navy pilots film Tic-Tac UAP. The footage remains unexplained by the Pentagon", category: "UFO" },
  { year: "2013", title: "Snowden Revelations", description: "NSA mass surveillance of the entire internet confirmed by leaked documents", category: "Government" },
  { year: "2017", title: "'Oumuamua Detected", description: "First interstellar object accelerates out of our solar system without explanation", category: "Science" },
  { year: "2020", title: "Pentagon Confirms UAPs", description: "DoD officially releases Tic-Tac, Gimbal and Go Fast videos as authentic", category: "UFO" },
  { year: "Today", title: "Disclosure Era", description: "Congressional hearings, whistleblowers, and declassification reshape the conversation", category: "Government" },
];

export function getEvidenceLabel(score: number): { label: string; color: string } {
  if (score >= 80) return { label: "Strong Evidence", color: "text-green-400" };
  if (score >= 60) return { label: "Mixed Evidence", color: "text-yellow-400" };
  if (score >= 30) return { label: "Weak Evidence", color: "text-orange-400" };
  return { label: "Unsupported", color: "text-rt-muted" };
}

export function getCategoryColor(category: string): string {
  const map: Record<string, string> = {
    "Government": "bg-blue-900/40 text-blue-300 border-blue-700/40",
    "UFO": "bg-purple-900/40 text-purple-300 border-purple-700/40",
    "Unexplained": "bg-orange-900/40 text-orange-300 border-orange-700/40",
    "Ancient Mysteries": "bg-amber-900/40 text-amber-300 border-amber-700/40",
    "Historical": "bg-stone-800/60 text-stone-300 border-stone-600/40",
    "Science": "bg-cyan-900/40 text-cyan-300 border-cyan-700/40",
    "Urban Legends": "bg-pink-900/40 text-pink-300 border-pink-700/40",
    "Debunked": "bg-emerald-900/40 text-emerald-300 border-emerald-700/40",
  };
  return map[category] ?? "bg-rt-surface text-rt-muted border-rt-border";
}
