// Static data for investigations — in a real app this would come from Supabase

export interface Investigation {
  id: string;
  title: string;
  slug: string;
  description: string;
  category: string;
  evidenceScore: number;
  year?: string;
  wikiTitle: string;
  imageUrl?: string;
}

export const featuredInvestigation: Investigation = {
  id: "area-51",
  title: "Area 51: What Really Happened?",
  slug: "area-51",
  description:
    "Decades of secrecy surrounding the Nevada test site have spawned countless theories. Declassified documents reveal a more complex truth — but many questions remain unanswered.",
  category: "Government",
  evidenceScore: 74,
  year: "1955",
  wikiTitle: "Area 51",
};

// ── Full investigation dataset ────────────────────────────────────────────
export const allInvestigations: Investigation[] = [
  // UFO
  {
    id: "uss-nimitz",
    title: "USS Nimitz UFO Encounter",
    slug: "uss-nimitz",
    description: "In November 2004, US Navy pilots encountered a white Tic-Tac shaped object off San Diego that outperformed every known aircraft. Cmdr. David Fravor's testimony and gun-camera footage remain the most credible military UAP evidence on record.",
    category: "UFO",
    evidenceScore: 92,
    year: "2004",
    wikiTitle: "2004 USS Nimitz UFO incident",
  },
  {
    id: "belgium-ufo-wave",
    title: "Belgian UFO Wave",
    slug: "belgium-ufo-wave",
    description: "Between 1989 and 1990, over 13,500 people — including police and military — reported large triangular craft over Belgium. Two F-16s gave chase; the object performed manoeuvres no known aircraft could survive.",
    category: "UFO",
    evidenceScore: 71,
    year: "1989",
    wikiTitle: "Belgian UFO wave",
  },
  {
    id: "travis-walton",
    title: "Travis Walton Abduction",
    slug: "travis-walton",
    description: "On November 5, 1975, logger Travis Walton vanished in front of six witnesses after approaching a glowing disc in an Arizona forest. He reappeared five days later with fragmented memories of an alien craft. All seven men passed polygraph tests.",
    category: "UFO",
    evidenceScore: 44,
    year: "1975",
    wikiTitle: "Travis Walton incident",
  },
  {
    id: "uss-roosevelt",
    title: "USS Roosevelt 'Gimbal' Object",
    slug: "uss-roosevelt",
    description: "In 2015, pilots aboard USS Theodore Roosevelt filmed the now-famous 'Gimbal' UAP rotating against the wind at high altitude. The Defense Intelligence Agency confirmed the footage was real and unclassified.",
    category: "UFO",
    evidenceScore: 88,
    year: "2015",
    wikiTitle: "Pentagon UFO videos",
  },
  {
    id: "roswell",
    title: "The Roswell Incident",
    slug: "roswell",
    description: "A 1947 crash in New Mexico that changed how the world thinks about UFOs and government secrecy.",
    category: "UFO",
    evidenceScore: 68,
    year: "1947",
    wikiTitle: "Roswell UFO incident",
  },
  {
    id: "phoenix-lights",
    title: "The Phoenix Lights",
    slug: "phoenix-lights",
    description: "On March 13, 1997, thousands of Arizona residents reported a massive V-shaped formation of lights gliding silently across the night sky. The US Air Force offered an explanation — few believed it.",
    category: "UFO",
    evidenceScore: 61,
    year: "1997",
    wikiTitle: "Phoenix Lights",
  },
  {
    id: "rendlesham",
    title: "Rendlesham Forest Incident",
    slug: "rendlesham-forest",
    description: "Described as Britain's Roswell, US military personnel at RAF Woodbridge reported landing lights, a metallic craft, and radiation readings that have never been fully explained.",
    category: "UFO",
    evidenceScore: 55,
    year: "1980",
    wikiTitle: "Rendlesham Forest incident",
  },
  {
    id: "bob-lazar",
    title: "Bob Lazar: Area S-4 Whistleblower",
    slug: "bob-lazar",
    description: "Bob Lazar claims he worked on reverse-engineering alien propulsion systems at a secret facility near Area 51. His credentials were disputed — until some were quietly confirmed.",
    category: "UFO",
    evidenceScore: 38,
    year: "1989",
    wikiTitle: "Bob Lazar",
  },
  {
    id: "pentagon-uap",
    title: "Pentagon UAP Disclosure",
    slug: "pentagon-uap",
    description: "The US military officially released videos of Unidentified Aerial Phenomena in 2020 — the Tic Tac, Gimbal, and Go Fast videos. Congress continues to hold closed-door hearings.",
    category: "UFO",
    evidenceScore: 79,
    year: "2017",
    wikiTitle: "Pentagon UFO videos",
  },
  {
    id: "kecksburg",
    title: "Kecksburg UFO Crash",
    slug: "kecksburg-ufo",
    description: "On December 9, 1965, a fireball streaked across six US states before crashing in Kecksburg, Pennsylvania. Witnesses described an acorn-shaped metallic object. The military cordoned the area and removed something — officially it was a meteor.",
    category: "UFO",
    evidenceScore: 58,
    year: "1965",
    wikiTitle: "Kecksburg UFO incident",
  },
  {
    id: "cash-landrum",
    title: "Cash-Landrum Incident",
    slug: "cash-landrum",
    description: "On December 29, 1980, Betty Cash, Vickie Landrum and her grandson encountered a diamond-shaped craft emitting intense heat over a Texas highway. All three developed radiation-like symptoms. The US Army denied involvement despite 23 Chinook helicopters being sighted surrounding the craft.",
    category: "UFO",
    evidenceScore: 67,
    year: "1980",
    wikiTitle: "Cash-Landrum incident",
  },
  {
    id: "ariel-school",
    title: "Ariel School UFO Encounter",
    slug: "ariel-school",
    description: "On September 16, 1994, 62 children at a Zimbabwe primary school reported witnessing a craft land in bushes beside their playground. A small being walked toward them. Harvard psychiatrist Dr. John Mack interviewed the children and found no evidence of fabrication.",
    category: "UFO",
    evidenceScore: 72,
    year: "1994",
    wikiTitle: "Ariel School UFO incident",
  },
  {
    id: "jal1628",
    title: "JAL Flight 1628 UFO Sighting",
    slug: "jal-flight-1628",
    description: "On November 17, 1986, the crew of Japan Air Lines cargo flight 1628 reported a massive object — estimated at twice the size of an aircraft carrier — pacing their plane for 50 minutes over Alaska. The FAA opened an official investigation. The captain was reassigned.",
    category: "UFO",
    evidenceScore: 74,
    year: "1986",
    wikiTitle: "Japan Air Lines flight 1628 incident",
  },
  {
    id: "westall-66",
    title: "Westall '66 UFO Encounter",
    slug: "westall-66",
    description: "On April 6, 1966, more than 200 students and teachers at two Melbourne schools watched a silver disc descend into a nearby field, then ascend and vanish at high speed. Multiple witnesses approached the object on the ground. Teachers were reportedly told to stay silent. The Australian Department of Air investigated and classified the findings.",
    category: "UFO",
    evidenceScore: 76,
    year: "1966",
    wikiTitle: "Westall UFO encounter",
  },
  {
    id: "tehran-ufo",
    title: "1976 Tehran UFO Incident",
    slug: "tehran-ufo",
    description: "On September 19, 1976, two Iranian F-4 Phantom jets scrambled to intercept a brilliant UAP over Tehran. As each pilot attempted to fire, their weapons systems failed and instruments went dark. The Defence Intelligence Agency filed a detailed official report rating the case as an outstanding example of a UFO encounter backed by multiple forms of corroborating evidence.",
    category: "UFO",
    evidenceScore: 81,
    year: "1976",
    wikiTitle: "1976 Tehran UFO incident",
  },
  {
    id: "shag-harbour",
    title: "Shag Harbour Incident",
    slug: "shag-harbour",
    description: "On October 4, 1967, multiple witnesses — including RCMP officers — watched four orange lights hover then crash into the water off Nova Scotia. Divers found no wreckage. Declassified documents confirmed a joint Canadian-US military investigation tracked an unidentified submerged object for days before it vanished.",
    category: "UFO",
    evidenceScore: 69,
    year: "1967",
    wikiTitle: "Shag Harbour incident",
  },
  {
    id: "lubbock-lights",
    title: "The Lubbock Lights",
    slug: "lubbock-lights",
    description: "On August 25, 1951, a formation of 20–30 softly glowing lights swept silently over Lubbock, Texas in a perfect semicircle. Four Texas Tech professors witnessed the first pass. A student photographed five separate passes in a single night. Project Blue Book investigated and officially listed the case as 'unexplained'.",
    category: "UFO",
    evidenceScore: 53,
    year: "1951",
    wikiTitle: "Lubbock Lights",
  },
  // Government
  {
    id: "operation-northwoods",
    title: "Operation Northwoods",
    slug: "operation-northwoods",
    description: "In 1962, the Joint Chiefs of Staff signed off on a plan to stage false-flag terrorist attacks on American citizens — including shooting down a civilian airliner — to justify an invasion of Cuba. President Kennedy rejected it.",
    category: "Government",
    evidenceScore: 99,
    year: "1962",
    wikiTitle: "Operation Northwoods",
  },
  {
    id: "prism",
    title: "PRISM: NSA Mass Surveillance",
    slug: "nsa-prism",
    description: "In 2013, Edward Snowden leaked classified documents revealing the NSA had built a secret system to collect internet communications from nine major US tech companies — Microsoft, Google, Apple, Facebook and others — without individual warrants.",
    category: "Government",
    evidenceScore: 100,
    year: "2013",
    wikiTitle: "PRISM",
  },
  {
    id: "cia-heart-attack-gun",
    title: "CIA Assassination Weapons",
    slug: "cia-assassination-weapons",
    description: "In 1975, CIA Director William Colby revealed to the Church Committee that the agency had developed an untraceable dart gun capable of inducing a fatal heart attack. The dart dissolved on impact, leaving no trace of poison in autopsy.",
    category: "Government",
    evidenceScore: 97,
    year: "1975",
    wikiTitle: "Heart attack gun",
  },
  {
    id: "project-artichoke",
    title: "Project ARTICHOKE",
    slug: "project-artichoke",
    description: "Before MK Ultra, the CIA's Project ARTICHOKE explored whether a person could be compelled to carry out an assassination then forget they had done it. Declassified documents confirm experiments on prisoners and unwitting soldiers.",
    category: "Government",
    evidenceScore: 94,
    year: "1951",
    wikiTitle: "Project ARTICHOKE",
  },
  {
    id: "area-51",
    title: "Area 51: What Really Happened?",
    slug: "area-51",
    description: "Decades of secrecy surrounding the Nevada test site have spawned countless theories. Declassified documents reveal a more complex truth — but many questions remain unanswered.",
    category: "Government",
    evidenceScore: 74,
    year: "1955",
    wikiTitle: "Area 51",
  },
  {
    id: "mkultra",
    title: "MK Ultra",
    slug: "mk-ultra",
    description: "The CIA's secret mind control program that tested LSD and psychological torture on unwitting subjects for over a decade.",
    category: "Government",
    evidenceScore: 91,
    year: "1953",
    wikiTitle: "Project MKUltra",
  },
  {
    id: "philadelphia-experiment",
    title: "The Philadelphia Experiment",
    slug: "philadelphia-experiment",
    description: "Did the US Navy render a warship invisible and teleport it in 1943? Declassified records raise more questions than answers.",
    category: "Government",
    evidenceScore: 22,
    year: "1943",
    wikiTitle: "Philadelphia Experiment",
  },
  {
    id: "jfk",
    title: "JFK Assassination Files",
    slug: "jfk-assassination",
    description: "Newly released CIA documents add fresh layers to one of history's most scrutinised events. Key records remain classified until 2039.",
    category: "Government",
    evidenceScore: 71,
    year: "1963",
    wikiTitle: "Assassination of John F. Kennedy",
  },
  {
    id: "operation-paperclip",
    title: "Operation Paperclip",
    slug: "operation-paperclip",
    description: "After World War II, the US secretly recruited over 1,600 Nazi scientists — including Wernher von Braun — to work on military and space programs. Most were given falsified records.",
    category: "Government",
    evidenceScore: 96,
    year: "1945",
    wikiTitle: "Operation Paperclip",
  },
  {
    id: "cointelpro",
    title: "COINTELPRO",
    slug: "cointelpro",
    description: "Declassified FBI documents confirmed a decade-long covert program to surveil, infiltrate, and disrupt civil rights groups, anti-war activists, and political organisations.",
    category: "Government",
    evidenceScore: 98,
    year: "1956",
    wikiTitle: "COINTELPRO",
  },
  {
    id: "tuskegee",
    title: "Tuskegee Syphilis Study",
    slug: "tuskegee-study",
    description: "For 40 years, the US Public Health Service deliberately withheld treatment from 399 Black men with syphilis to study disease progression. The experiment ended only after a whistleblower came forward.",
    category: "Government",
    evidenceScore: 99,
    year: "1932",
    wikiTitle: "Tuskegee Syphilis Study",
  },
  {
    id: "operation-gladio",
    title: "Operation Gladio",
    slug: "operation-gladio",
    description: "A NATO-backed network of secret 'stay-behind' armies operated across Western Europe for decades during the Cold War, later linked to false-flag terrorism, political assassinations, and bombings designed to discredit the left. Confirmed by Italian prime minister Giulio Andreotti in 1990.",
    category: "Government",
    evidenceScore: 96,
    year: "1956",
    wikiTitle: "Operation Gladio",
  },
  {
    id: "gulf-of-tonkin",
    title: "Gulf of Tonkin Deception",
    slug: "gulf-of-tonkin",
    description: "The 1964 Gulf of Tonkin incident — in which North Vietnamese boats allegedly attacked US destroyers — was used to justify the Vietnam War. Declassified NSA documents and Robert McNamara's own testimony confirmed the second attack almost certainly never happened.",
    category: "Government",
    evidenceScore: 98,
    year: "1964",
    wikiTitle: "Gulf of Tonkin incident",
  },
  {
    id: "iran-contra",
    title: "Iran-Contra Affair",
    slug: "iran-contra",
    description: "Senior Reagan administration officials secretly facilitated arms sales to Iran — under an arms embargo — and diverted the profits to fund Nicaraguan Contra rebels in defiance of a congressional ban. Fourteen officials were indicted. Most convictions were later overturned.",
    category: "Government",
    evidenceScore: 99,
    year: "1986",
    wikiTitle: "Iran–Contra affair",
  },
  {
    id: "echelon",
    title: "Project ECHELON",
    slug: "project-echelon",
    description: "The Five Eyes intelligence alliance — US, UK, Canada, Australia and New Zealand — built a global surveillance network capable of intercepting virtually all satellite, phone and internet traffic. Denied for decades, it was confirmed by a 2001 European Parliament investigation.",
    category: "Government",
    evidenceScore: 95,
    year: "1971",
    wikiTitle: "ECHELON",
  },
  {
    id: "operation-mockingbird",
    title: "Operation Mockingbird",
    slug: "operation-mockingbird",
    description: "Beginning in the 1950s, the CIA secretly recruited journalists at major US outlets — including the Washington Post, Time, and CBS — to publish stories serving intelligence objectives. Senate Church Committee hearings in 1975 confirmed the programme. The CIA director testified that over 400 American journalists had secretly carried out agency assignments.",
    category: "Government",
    evidenceScore: 89,
    year: "1950",
    wikiTitle: "Operation Mockingbird",
  },
  {
    id: "mkultra-cameron",
    title: "MKULTRA: The Cameron Experiments",
    slug: "mkultra-cameron",
    description: "Between 1957 and 1964, CIA-funded psychiatrist Dr. Ewen Cameron subjected unwitting patients at McGill University to 'psychic driving' — weeks of drug-induced sleep, electroconvulsive therapy at up to 40 times normal intensity, and looped audio messages designed to erase and reprogram identity. Canada paid compensation to survivors in 1992.",
    category: "Government",
    evidenceScore: 97,
    year: "1957",
    wikiTitle: "Donald Ewen Cameron",
  },
  {
    id: "operation-chaos",
    title: "Operation CHAOS",
    slug: "operation-chaos",
    description: "From 1967 to 1974, the CIA ran a secret domestic surveillance programme that built files on over 7,200 US citizens and 1,000 organisations — in direct violation of the CIA's charter. Targets included Vietnam War protesters, journalists, and civil rights activists. The programme was exposed by the Church Committee in 1975.",
    category: "Government",
    evidenceScore: 95,
    year: "1967",
    wikiTitle: "Operation CHAOS",
  },
  {
    id: "unit-731",
    title: "Unit 731: Japan's Secret Bioweapons Programme",
    slug: "unit-731",
    description: "During World War II, Imperial Japan's covert Unit 731 conducted biological and chemical warfare experiments on an estimated 3,000–12,000 prisoners — including vivisection without anaesthetic, plague testing, and frostbite experiments. In exchange for research data, the US granted immunity to all researchers and suppressed the programme until the 1980s.",
    category: "Government",
    evidenceScore: 98,
    year: "1937",
    wikiTitle: "Unit 731",
  },
  // Unexplained
  {
    id: "oak-island",
    title: "Oak Island Money Pit",
    slug: "oak-island",
    description: "Since 1795, treasure hunters have been digging on a small Nova Scotia island after a teenager found a circular depression in the ground. The pit floods automatically at 33 feet. Six people have died trying to reach the bottom. Nothing definitive has ever been found.",
    category: "Unexplained",
    evidenceScore: 41,
    year: "1795",
    wikiTitle: "Oak Island",
  },
  {
    id: "d-b-cooper-briefcase",
    title: "The Zodiac Cipher",
    slug: "zodiac-cipher",
    description: "The Zodiac Killer sent four encrypted messages to police and newspapers between 1969 and 1974. Three remain unsolved. The killer was never caught. The 340-character cipher went unsolved for 51 years until a team of amateur cryptologists cracked it in 2020.",
    category: "Unexplained",
    evidenceScore: 64,
    year: "1969",
    wikiTitle: "Zodiac Killer",
  },
  {
    id: "patomskiy-crater",
    title: "Patomskiy Crater",
    slug: "patomskiy-crater",
    description: "A massive conical mound of shattered limestone in the remote Siberian taiga, 40 metres high and 160 metres across. Local Yakuts call it the Eagle's Nest and refuse to go near it. Animals avoid it. The origin is unknown.",
    category: "Unexplained",
    evidenceScore: 53,
    year: "1949",
    wikiTitle: "Patomskiy crater",
  },
  {
    id: "spontaneous-combustion",
    title: "Spontaneous Human Combustion",
    slug: "spontaneous-human-combustion",
    description: "Hundreds of documented cases describe human bodies reduced to ash — while surrounding furniture remains intact. The 'wick effect' hypothesis is disputed. Some cases leave no forensic explanation.",
    category: "Unexplained",
    evidenceScore: 36,
    wikiTitle: "Spontaneous human combustion",
  },
  {
    id: "dyatlov",
    title: "Dyatlov Pass Incident",
    slug: "dyatlov-pass",
    description: "Nine experienced hikers died mysteriously in the Ural Mountains. The cause remains disputed despite a 2019 Russian government investigation.",
    category: "Unexplained",
    evidenceScore: 55,
    year: "1959",
    wikiTitle: "Dyatlov Pass incident",
  },
  {
    id: "bermuda-triangle",
    title: "Bermuda Triangle",
    slug: "bermuda-triangle",
    description: "Recent oceanographic surveys offer new explanations for the mysterious disappearances in this stretch of the Atlantic.",
    category: "Unexplained",
    evidenceScore: 45,
    wikiTitle: "Bermuda Triangle",
  },
  {
    id: "havana-syndrome",
    title: "Havana Syndrome",
    slug: "havana-syndrome",
    description: "Since 2016, hundreds of US diplomats and intelligence officers have reported debilitating neurological symptoms. The CIA concluded most cases have no foreign cause — but 24 remain unexplained.",
    category: "Unexplained",
    evidenceScore: 62,
    year: "2016",
    wikiTitle: "Havana syndrome",
  },
  {
    id: "taos-hum",
    title: "The Taos Hum",
    slug: "taos-hum",
    description: "Since the early 1990s, residents of Taos, New Mexico have reported a persistent low-frequency hum audible to only 2% of the population. Multiple government investigations failed to identify the source.",
    category: "Unexplained",
    evidenceScore: 58,
    year: "1991",
    wikiTitle: "Taos Hum",
  },
  {
    id: "hessdalen-lights",
    title: "Hessdalen Lights",
    slug: "hessdalen-lights",
    description: "Since the 1930s, unexplained lights have appeared in a remote Norwegian valley — sometimes stationary for over an hour, sometimes moving at extraordinary speed. A scientific monitoring station has been recording them since 1983. Multiple hypotheses exist; none are conclusive.",
    category: "Unexplained",
    evidenceScore: 77,
    year: "1930s",
    wikiTitle: "Hessdalen lights",
  },
  {
    id: "tamam-shud",
    title: "Tamam Shud: The Somerton Man",
    slug: "tamam-shud",
    description: "On December 1, 1948, an unidentified man was found dead on Somerton Beach, Australia. All labels had been removed from his clothes. Hidden in a secret pocket was a scrap of paper reading 'Tamám Shud' — Persian for 'ended'. A 2022 DNA study identified him as Carl 'Charles' Webb, but the mystery of his death remains unsolved.",
    category: "Unexplained",
    evidenceScore: 61,
    year: "1948",
    wikiTitle: "Tamam Shud case",
  },
  {
    id: "salish-sea-feet",
    title: "Salish Sea Human Foot Discoveries",
    slug: "salish-sea-feet",
    description: "Since 2007, over 20 human feet — still inside running shoes — have washed ashore along the coasts of British Columbia and Washington state. Investigators have identified most but not all. The pattern of detachment points to a body of water where multiple people went missing, but no mass-casualty event has been confirmed.",
    category: "Unexplained",
    evidenceScore: 68,
    year: "2007",
    wikiTitle: "Salish Sea human foot discoveries",
  },
  {
    id: "black-knight",
    title: "The Black Knight Satellite",
    slug: "black-knight-satellite",
    description: "Since the 1950s, there have been claims of an unidentified object in polar orbit predating any known satellite — allegedly detected by Tesla, photographed by NASA, and tracked by the US military. Officially classified as space debris, the object's true origin remains contested.",
    category: "Unexplained",
    evidenceScore: 23,
    year: "1954",
    wikiTitle: "Black Knight satellite conspiracy theory",
  },
  {
    id: "numbers-stations",
    title: "Numbers Stations",
    slug: "numbers-stations",
    description: "For over 70 years, shortwave radio frequencies worldwide have broadcast streams of numbers read by robotic or child-like voices — then fallen silent. Governments universally deny operating them. One station, UVB-76 ('The Buzzer'), has broadcast almost continuously since 1973. Their purpose and operators remain officially unacknowledged.",
    category: "Unexplained",
    evidenceScore: 72,
    year: "1950s",
    wikiTitle: "Numbers station",
  },
  {
    id: "hinterkaifeck",
    title: "The Hinterkaifeck Murders",
    slug: "hinterkaifeck",
    description: "In March 1922, all six members of the Gruber family were murdered on their remote Bavarian farm. The killer had been living in the loft for days before the attack — and stayed for several days after, feeding the cattle. Footprints in the snow led to the farm but none led away. The case was never solved.",
    category: "Unexplained",
    evidenceScore: 61,
    year: "1922",
    wikiTitle: "Hinterkaifeck murders",
  },
  {
    id: "flannan-isles",
    title: "Flannan Isles Lighthouse Mystery",
    slug: "flannan-isles",
    description: "On December 15, 1900, a relief vessel arrived at the Flannan Isles lighthouse to find all three experienced keepers had vanished. The last log entry described a storm of unprecedented violence — on a day meteorological records showed was calm. No bodies were ever found and no explanation has been confirmed.",
    category: "Unexplained",
    evidenceScore: 58,
    year: "1900",
    wikiTitle: "Flannan Isles",
  },
  {
    id: "cicada-3301",
    title: "Cicada 3301",
    slug: "cicada-3301",
    description: "Beginning January 4, 2012, cryptographic puzzles appeared online claiming to recruit 'highly intelligent individuals'. The challenges spanned cybersecurity, mathematics, philosophy, and literature across physical locations on four continents. Three annual cycles were confirmed. The organisation behind it has never been publicly identified.",
    category: "Unexplained",
    evidenceScore: 68,
    year: "2012",
    wikiTitle: "Cicada 3301",
  },
  // Ancient Mysteries
  {
    id: "sacsayhuaman",
    title: "Sacsayhuamán Fortress",
    slug: "sacsayhuaman",
    description: "The Inca fortress above Cusco is built from stones weighing up to 125 tonnes, fitted together without mortar so precisely that a razor blade cannot pass between them. Modern engineers cannot explain how they were transported or shaped with only stone tools.",
    category: "Ancient Mysteries",
    evidenceScore: 73,
    year: "1438",
    wikiTitle: "Sacsayhuamán",
  },
  {
    id: "antikythera",
    title: "The Antikythera Mechanism",
    slug: "antikythera-mechanism",
    description: "A 2,000-year-old bronze device recovered from a Greek shipwreck that could calculate the positions of the sun, moon and planets with extraordinary accuracy. The technology it represents wouldn't reappear in Europe for another 1,400 years.",
    category: "Ancient Mysteries",
    evidenceScore: 95,
    year: "100 BCE",
    wikiTitle: "Antikythera mechanism",
  },
  {
    id: "baalbek",
    title: "Baalbek Megaliths",
    slug: "baalbek-megaliths",
    description: "The Roman temple complex at Baalbek, Lebanon sits on a platform of stone blocks weighing over 800 tonnes each — among the heaviest objects ever moved by humans. No ancient crane or machine capable of lifting them has ever been identified.",
    category: "Ancient Mysteries",
    evidenceScore: 67,
    year: "50 BCE",
    wikiTitle: "Baalbek",
  },
  {
    id: "piri-reis",
    title: "Piri Reis Map",
    slug: "piri-reis-map",
    description: "A 1513 Ottoman map that appears to accurately depict the coastline of Antarctica — 300 years before the continent was officially discovered. The map's source charts are unknown. Modern researchers continue to debate its accuracy and implications.",
    category: "Ancient Mysteries",
    evidenceScore: 49,
    year: "1513",
    wikiTitle: "Piri Reis map",
  },
  {
    id: "atlantis",
    title: "Atlantis: Lost Civilization",
    slug: "atlantis",
    description: "Plato described an advanced civilization swallowed by the sea. Archaeologists still debate whether this was allegory, myth, or memory.",
    category: "Ancient Mysteries",
    evidenceScore: 28,
    year: "360 BCE",
    wikiTitle: "Atlantis",
  },
  {
    id: "nazca-lines",
    title: "Nazca Lines Mystery",
    slug: "nazca-lines",
    description: "Ancient geoglyphs in Peru so large they can only be appreciated from the sky. Who made them, and why?",
    category: "Ancient Mysteries",
    evidenceScore: 62,
    year: "500 BCE",
    wikiTitle: "Nazca Lines",
  },
  {
    id: "stonehenge",
    title: "Stonehenge",
    slug: "stonehenge",
    description: "The massive stones were transported hundreds of miles from Wales without wheels or iron tools. New research suggests the site was simultaneously a burial ground, healing centre, and astronomical calendar.",
    category: "Ancient Mysteries",
    evidenceScore: 71,
    year: "3000 BCE",
    wikiTitle: "Stonehenge",
  },
  {
    id: "great-pyramid",
    title: "Great Pyramid of Giza",
    slug: "great-pyramid",
    description: "Constructed with such precision that a human hair cannot be inserted between the casing stones, the Great Pyramid still defies our understanding of ancient engineering capabilities.",
    category: "Ancient Mysteries",
    evidenceScore: 75,
    year: "2560 BCE",
    wikiTitle: "Great Pyramid of Giza",
  },
  {
    id: "gobekli-tepe",
    title: "Göbekli Tepe",
    slug: "gobekli-tepe",
    description: "Built 11,500 years ago by hunter-gatherers with no known writing, metal tools, or agriculture — 6,000 years before Stonehenge. It rewrites everything we thought we knew about civilisation.",
    category: "Ancient Mysteries",
    evidenceScore: 88,
    year: "9600 BCE",
    wikiTitle: "Göbekli Tepe",
  },
  {
    id: "easter-island",
    title: "Easter Island Statues",
    slug: "easter-island",
    description: "Nearly 900 massive stone statues were carved and transported across a remote Pacific island by a civilisation that then seemingly collapsed — raising questions about environmental overextension.",
    category: "Ancient Mysteries",
    evidenceScore: 69,
    year: "1250 CE",
    wikiTitle: "Easter Island",
  },
  {
    id: "yonaguni",
    title: "Yonaguni Monument",
    slug: "yonaguni-monument",
    description: "A massive underwater rock formation off the coast of Japan with flat planes, right angles, and apparent staircases. Discovered in 1987, it has divided geologists and archaeologists ever since. If man-made, it would pre-date every known civilization and require rewriting the history of human settlement.",
    category: "Ancient Mysteries",
    evidenceScore: 54,
    year: "1987",
    wikiTitle: "Yonaguni Monument",
  },
  {
    id: "baghdad-battery",
    title: "The Baghdad Battery",
    slug: "baghdad-battery",
    description: "A 2,000-year-old clay pot found near Baghdad contains a copper cylinder and iron rod. When filled with an acidic liquid, it produces up to 1.5 volts of electricity. If intentional, it predates Alessandro Volta's battery by 1,800 years. No one has conclusively determined what it was actually used for.",
    category: "Ancient Mysteries",
    evidenceScore: 58,
    year: "250 BCE",
    wikiTitle: "Baghdad Battery",
  },
  {
    id: "pumapunku",
    title: "Pumapunku: Impossible Stonework",
    slug: "pumapunku",
    description: "At 3,800 metres above sea level in Bolivia, the Tiwanaku site contains H-shaped stone blocks with interlocking channels machined to tolerances of 0.1mm — by a culture with no writing, no iron tools, and no wheel. Modern analysis suggests they used harder stone tools and abrasives, but the precision remains extraordinary.",
    category: "Ancient Mysteries",
    evidenceScore: 69,
    year: "500 CE",
    wikiTitle: "Pumapunku",
  },
  {
    id: "longyou-caves",
    title: "The Longyou Caves",
    slug: "longyou-caves",
    description: "In 1992, villagers in China's Zhejiang province drained a pond to reveal a vast artificial cave system dating to at least 212 BCE. The caves cover 30,000 square metres with ceilings up to 30 metres high, carved in a consistent parallel chisel pattern. No historical record, no tools, no rubble, and no mention in any ancient text explains their existence or purpose.",
    category: "Ancient Mysteries",
    evidenceScore: 82,
    year: "212 BCE",
    wikiTitle: "Longyou Caves",
  },
  {
    id: "derinkuyu",
    title: "Derinkuyu Underground City",
    slug: "derinkuyu",
    description: "Beneath Turkey's Cappadocia region lies an 18-storey underground city capable of housing 20,000 people — complete with ventilation shafts, wells, chapels, and massive circular stone doors. Carved from soft volcanic rock by an unknown civilisation, it was discovered in 1963 when a homeowner knocked through a wall and found a tunnel stretching into the dark.",
    category: "Ancient Mysteries",
    evidenceScore: 85,
    year: "800 BCE",
    wikiTitle: "Derinkuyu underground city",
  },
  {
    id: "richat-structure",
    title: "The Richat Structure",
    slug: "richat-structure",
    description: "A 50-kilometre-wide circular feature in the Sahara Desert, so geometrically perfect it was used as a landmark by early astronauts. Geologists classify it as an eroded dome — but its concentric symmetry, alternating rock layers, and diameter closely matching Plato's description of Atlantis have made it the focus of serious alternative research.",
    category: "Ancient Mysteries",
    evidenceScore: 42,
    wikiTitle: "Richat Structure",
  },
  {
    id: "abydos-helicopter",
    title: "The Abydos Helicopter Carvings",
    slug: "abydos-helicopter",
    description: "Temple carvings at Abydos, Egypt, appear to depict a helicopter, submarine, and aircraft among hieroglyphics dating to approximately 3,000 years ago. Egyptologists attribute the images to a palimpsest — a partially re-carved cartouche that created ambiguous shapes when the plaster fell away. Believers cite them as evidence of ancient advanced technology.",
    category: "Ancient Mysteries",
    evidenceScore: 19,
    year: "1300 BCE",
    wikiTitle: "Abydos helicopter",
  },
  // Historical
  {
    id: "amelia-earhart",
    title: "Amelia Earhart's Disappearance",
    slug: "amelia-earhart",
    description: "On July 2, 1937, pioneer aviator Amelia Earhart and navigator Fred Noonan vanished over the Pacific on the final leg of a round-the-world flight. New forensic analysis of a 1940 skeleton and radio transmissions suggests they survived the crash — for a while.",
    category: "Historical",
    evidenceScore: 61,
    year: "1937",
    wikiTitle: "Amelia Earhart",
  },
  {
    id: "skripals",
    title: "Salisbury Novichok Poisonings",
    slug: "salisbury-novichok",
    description: "In 2018, former Russian double-agent Sergei Skripal and his daughter were poisoned with a military-grade nerve agent on a British street. The UK government attributed the attack to Russian intelligence. Moscow denied involvement. One British civilian died.",
    category: "Historical",
    evidenceScore: 91,
    year: "2018",
    wikiTitle: "Poisoning of Sergei and Yulia Skripal",
  },
  {
    id: "princes-tower",
    title: "The Princes in the Tower",
    slug: "princes-in-the-tower",
    description: "In 1483, King Edward IV's two young sons were placed in the Tower of London by their uncle — and vanished from history. Richard III was crowned shortly after. No bodies were officially identified for centuries. New DNA analysis is ongoing.",
    category: "Historical",
    evidenceScore: 47,
    year: "1483",
    wikiTitle: "Princes in the Tower",
  },
  {
    id: "sodder-children",
    title: "The Sodder Children Disappearance",
    slug: "sodder-children",
    description: "On Christmas Eve 1945, a fire destroyed the Sodder family home in West Virginia. Five of the ten children were never found — no remains, no trace. The family believed they escaped and were kidnapped. The case was never solved.",
    category: "Historical",
    evidenceScore: 55,
    year: "1945",
    wikiTitle: "Sodder children",
  },
  {
    id: "voynich",
    title: "The Voynich Manuscript",
    slug: "voynich-manuscript",
    description: "An undeciphered illustrated book written in an unknown script, possibly from the 15th century. Every major cryptanalyst and codebreaker has failed to crack it.",
    category: "Historical",
    evidenceScore: 38,
    wikiTitle: "Voynich manuscript",
  },
  {
    id: "mary-celeste",
    title: "Mary Celeste",
    slug: "mary-celeste",
    description: "In 1872 the brigantine Mary Celeste was found adrift in the Atlantic, perfectly seaworthy, with food on the table — but completely abandoned. The crew of ten was never found.",
    category: "Historical",
    evidenceScore: 52,
    year: "1872",
    wikiTitle: "Mary Celeste",
  },
  {
    id: "roanoke",
    title: "Lost Colony of Roanoke",
    slug: "roanoke-colony",
    description: "In 1590, the governor of Roanoke Island returned from England to find the colony of 115 men, women, and children had completely vanished, leaving only the word CROATOAN carved into a post.",
    category: "Historical",
    evidenceScore: 60,
    year: "1590",
    wikiTitle: "Roanoke Colony",
  },
  {
    id: "jack-the-ripper",
    title: "Jack the Ripper",
    slug: "jack-the-ripper",
    description: "The unidentified serial killer who murdered at least five women in Whitechapel in 1888 has inspired over 100 named suspects and generated more theories than any cold case in history.",
    category: "Historical",
    evidenceScore: 44,
    year: "1888",
    wikiTitle: "Jack the Ripper",
  },
  {
    id: "db-cooper",
    title: "D.B. Cooper",
    slug: "db-cooper",
    description: "In 1971, a man hijacked a Northwest Orient flight, extorted $200,000 in ransom, and parachuted into a remote Pacific Northwest wilderness — never to be seen again. The only unsolved air piracy case in US history.",
    category: "Historical",
    evidenceScore: 66,
    year: "1971",
    wikiTitle: "D. B. Cooper",
  },
  {
    id: "dancing-plague",
    title: "The Dancing Plague of 1518",
    slug: "dancing-plague-1518",
    description: "In July 1518, a woman in Strasbourg began dancing in the street and could not stop. Within a month, around 400 people had joined her. Several danced themselves to death. Physicians diagnosed it as 'hot blood' and prescribed more dancing. The cause — ergot poisoning, mass hysteria, or something else — is still debated.",
    category: "Historical",
    evidenceScore: 83,
    year: "1518",
    wikiTitle: "Dancing plague of 1518",
  },
  {
    id: "black-dahlia",
    title: "The Black Dahlia Murder",
    slug: "black-dahlia",
    description: "On January 15, 1947, the body of 22-year-old Elizabeth Short was found in a Los Angeles vacant lot, severed at the waist and completely drained of blood. The body had been surgically cleaned, posed, and the face cut into a Glasgow smile. The murder was never solved and remains the most famous cold case in LAPD history.",
    category: "Historical",
    evidenceScore: 52,
    year: "1947",
    wikiTitle: "Black Dahlia",
  },
  {
    id: "isdal-woman",
    title: "The Isdal Woman",
    slug: "isdal-woman",
    description: "In November 1970, a burnt body was found in a Norwegian valley known as the Valley of Death. The woman carried multiple false identities across Europe. Her fingerprints had been ground off. Labels were removed from her clothes. Norwegian police closed the case as suicide in 1971 and kept it classified for decades.",
    category: "Historical",
    evidenceScore: 59,
    year: "1970",
    wikiTitle: "Isdal Woman",
  },
  {
    id: "dybbuk-box",
    title: "The Dybbuk Box",
    slug: "dybbuk-box",
    description: "A wine cabinet sold on eBay in 2003 with a note claiming it housed a malevolent spirit. Every owner reported nightmares, illness, and unexplained phenomena. It has since been studied by paranormal researchers and forms the basis of a Hollywood film. Its provenance is documented — its effects remain disputed.",
    category: "Historical",
    evidenceScore: 12,
    year: "2003",
    wikiTitle: "Dybbuk box",
  },
  {
    id: "olof-palme",
    title: "Assassination of Olof Palme",
    slug: "olof-palme",
    description: "Swedish Prime Minister Olof Palme was shot dead on a Stockholm street on February 28, 1986 — with no bodyguards. Despite 130 named suspects and 34 years of investigation, the case was closed in 2020 by naming a dead man as the perpetrator. Multiple investigators remain unconvinced, and Swedish intelligence files linked to the case are still classified.",
    category: "Historical",
    evidenceScore: 71,
    year: "1986",
    wikiTitle: "Assassination of Olof Palme",
  },
  {
    id: "harold-holt",
    title: "Disappearance of Harold Holt",
    slug: "harold-holt",
    description: "On December 17, 1967, Australian Prime Minister Harold Holt walked into the surf at Cheviot Beach and was never seen again. No body was found. Persistent theories — including defection to China via submarine — were fuelled by declassified ASIO files revealing Holt had passed information to Chinese intelligence contacts.",
    category: "Historical",
    evidenceScore: 54,
    year: "1967",
    wikiTitle: "Harold Holt",
  },
  {
    id: "axeman-new-orleans",
    title: "The Axeman of New Orleans",
    slug: "axeman-new-orleans",
    description: "Between 1918 and 1919, an unknown assailant entered homes and attacked residents with their own axes. A letter published in New Orleans newspapers promised: 'Those who play jazz shall be spared.' On the announced date, jazz played from every venue in the city all night. The killer murdered at least 12 people and was never identified.",
    category: "Historical",
    evidenceScore: 66,
    year: "1918",
    wikiTitle: "Axeman of New Orleans",
  },
  {
    id: "max-headroom-hijack-hist",
    title: "The Zodiac Killer's Last Letter",
    slug: "zodiac-last-letter",
    description: "In January 1974, the Zodiac Killer sent what is believed to be his final communication — a card referencing the musical 'The Exorcist' and claiming a body count of 37. He was never caught, never identified, and never heard from again. The gap between his last confirmed killing in 1969 and this letter has never been explained.",
    category: "Historical",
    evidenceScore: 72,
    year: "1974",
    wikiTitle: "Zodiac Killer",
  },
  // Science
  {
    id: "fast-radio-bursts",
    title: "Fast Radio Bursts",
    slug: "fast-radio-bursts",
    description: "Millisecond-long pulses of radio energy from deep space so powerful they release more energy than the sun emits in a year. Some repeat on precise schedules. Their origin — natural or otherwise — is one of astrophysics' biggest open questions.",
    category: "Science",
    evidenceScore: 78,
    year: "2007",
    wikiTitle: "Fast radio burst",
  },
  {
    id: "fermi-paradox",
    title: "The Fermi Paradox",
    slug: "fermi-paradox",
    description: "If the universe contains billions of Earth-like planets and life arose easily, where is everyone? The absence of detectable alien civilisations contradicts statistical probability. Every proposed solution raises deeper questions.",
    category: "Science",
    evidenceScore: 81,
    year: "1950",
    wikiTitle: "Fermi paradox",
  },
  {
    id: "oumuamua",
    title: "'Oumuamua: Visitor from Beyond",
    slug: "oumuamua",
    description: "The first interstellar object detected passing through our solar system accelerated away from the sun without any observable outgassing — behaviour no comet or asteroid should exhibit. Harvard astronomer Avi Loeb argued it could be artificial in origin.",
    category: "Science",
    evidenceScore: 63,
    year: "2017",
    wikiTitle: "ʻOumuamua",
  },
  {
    id: "orch-or",
    title: "Quantum Consciousness",
    slug: "quantum-consciousness",
    description: "Physicists Penrose and Hameroff proposed that consciousness arises from quantum computations in neural microtubules. If correct, it would imply that the mind cannot be fully replicated in silicon — and that reality depends on the observer.",
    category: "Science",
    evidenceScore: 42,
    year: "1994",
    wikiTitle: "Orchestrated objective reduction",
  },
  {
    id: "tunguska",
    title: "Tunguska Event",
    slug: "tunguska",
    description: "The largest impact event in recorded history. In 1908, something flattened 2,000 km² of Siberian forest without leaving a crater.",
    category: "Science",
    evidenceScore: 82,
    year: "1908",
    wikiTitle: "Tunguska event",
  },
  {
    id: "wow-signal",
    title: "The Wow! Signal",
    slug: "wow-signal",
    description: "On August 15, 1977, a radio telescope at Ohio State University detected a signal so powerful that astronomer Jerry Ehman scrawled 'Wow!' in the margin. It lasted 72 seconds and has never been detected again.",
    category: "Science",
    evidenceScore: 72,
    year: "1977",
    wikiTitle: "Wow! signal",
  },
  {
    id: "dark-matter",
    title: "Dark Matter",
    slug: "dark-matter",
    description: "Approximately 27% of the universe is made of a substance that emits no light, cannot be seen, and has never been directly detected — yet its gravitational effects shape every galaxy.",
    category: "Science",
    evidenceScore: 85,
    year: "1933",
    wikiTitle: "Dark matter",
  },
  {
    id: "ball-lightning",
    title: "Ball Lightning",
    slug: "ball-lightning",
    description: "Thousands of eyewitnesses over centuries have reported glowing orbs of light that move against the wind, pass through glass, and vanish suddenly. Science has no consensus explanation.",
    category: "Science",
    evidenceScore: 59,
    wikiTitle: "Ball lightning",
  },
  {
    id: "simulation-hypothesis",
    title: "The Simulation Hypothesis",
    slug: "simulation-hypothesis",
    description: "Philosopher Nick Bostrom's 2003 paper argued that if advanced civilisations can run ancestor simulations, we are almost certainly living in one. Elon Musk puts the odds at one in billions that we are in base reality. Physicists have identified potential computational limits in quantum mechanics that may support the theory.",
    category: "Science",
    evidenceScore: 46,
    year: "2003",
    wikiTitle: "Simulation hypothesis",
  },
  {
    id: "pioneer-anomaly",
    title: "The Pioneer Anomaly",
    slug: "pioneer-anomaly",
    description: "Both Pioneer 10 and 11 — launched in 1972 and 1973 — experienced an unexplained deceleration as they left the solar system, drifting slightly off their predicted trajectories. For 30 years it defied explanation. In 2012, thermal recoil force was identified as the cause — but the anomaly led to serious proposals for new physics.",
    category: "Science",
    evidenceScore: 88,
    year: "1972",
    wikiTitle: "Pioneer anomaly",
  },
  {
    id: "placebo-effect",
    title: "The Placebo Effect",
    slug: "placebo-effect",
    description: "Sugar pills have measurably reduced pain, shrunk tumours, and treated depression in clinical trials. Open-label placebos — where patients know they are taking a placebo — still work. The mechanism by which belief produces measurable physiological change is poorly understood and challenges the mind-body divide.",
    category: "Science",
    evidenceScore: 92,
    year: "1955",
    wikiTitle: "Placebo",
  },
  {
    id: "double-slit",
    title: "The Double-Slit Experiment",
    slug: "double-slit-experiment",
    description: "When a single particle is fired at a barrier with two slits, it passes through both simultaneously and creates an interference pattern — but only when no one is watching. The act of observation collapses the wave function and changes the outcome. Richard Feynman called it 'the only mystery' in quantum mechanics.",
    category: "Science",
    evidenceScore: 97,
    year: "1801",
    wikiTitle: "Double-slit experiment",
  },
  {
    id: "mpemba-effect",
    title: "The Mpemba Effect",
    slug: "mpemba-effect",
    description: "In 1963, Tanzanian schoolboy Erasto Mpemba noticed that hot ice cream mix froze faster than cold. Physicists have argued about it ever since. Under certain conditions, hot water demonstrably freezes faster than cold — in apparent violation of thermodynamic expectation. The mechanism remains disputed; the phenomenon has been independently replicated hundreds of times.",
    category: "Science",
    evidenceScore: 71,
    year: "1963",
    wikiTitle: "Mpemba effect",
  },
  {
    id: "cold-fusion",
    title: "Cold Fusion: The Fleischmann-Pons Affair",
    slug: "cold-fusion",
    description: "On March 23, 1989, electrochemists Fleischmann and Pons announced nuclear fusion at room temperature in a jar of heavy water. The announcement caused scientific pandemonium. Most replication attempts failed and the researchers were discredited — but a small community of scientists continues to report anomalous heat effects that mainstream physics cannot fully explain.",
    category: "Science",
    evidenceScore: 38,
    year: "1989",
    wikiTitle: "Cold fusion",
  },
  {
    id: "quantum-entanglement",
    title: "Quantum Entanglement",
    slug: "quantum-entanglement",
    description: "When two particles are entangled, measuring one instantly determines the state of the other — regardless of the distance between them. Einstein called it 'spooky action at a distance' and spent his career trying to disprove it. The 2022 Nobel Prize in Physics confirmed entanglement is real. How information appears to travel faster than light remains unexplained.",
    category: "Science",
    evidenceScore: 99,
    year: "1935",
    wikiTitle: "Quantum entanglement",
  },
  {
    id: "fine-tuned-universe",
    title: "The Fine-Tuned Universe",
    slug: "fine-tuned-universe",
    description: "Physics contains 26 fundamental constants — the speed of light, the mass of the electron, the strength of gravity. Alter any of them by as little as one part in 10⁶⁰ and complex matter, stars, and life become impossible. The probability of this arising by chance has driven serious scientists toward multiverse theory, intelligent design, and simulation hypothesis.",
    category: "Science",
    evidenceScore: 82,
    wikiTitle: "Fine-tuned universe",
  },
  // Urban Legends
  {
    id: "black-eyed-children",
    title: "Black-Eyed Children",
    slug: "black-eyed-children",
    description: "Since the 1980s, people across the world have reported encounters with child-sized figures with completely black eyes who ask to be let inside. The reports are strikingly consistent — and deeply unsettling. No confirmed origin exists.",
    category: "Urban Legends",
    evidenceScore: 8,
    year: "1988",
    wikiTitle: "Black-eyed children",
  },
  {
    id: "spring-heeled-jack",
    title: "Spring-Heeled Jack",
    slug: "spring-heeled-jack",
    description: "For over 60 years from 1837, witnesses across Victorian Britain reported a terrifying figure that leaped over rooftops, breathed blue flame, and attacked women. The sightings began in London and spread across the country. No explanation was ever found.",
    category: "Urban Legends",
    evidenceScore: 14,
    year: "1837",
    wikiTitle: "Spring-heeled Jack",
  },
  {
    id: "slender-man",
    title: "The Slender Man Origin",
    slug: "slender-man",
    description: "Created as an internet meme in 2009, Slender Man inspired two 12-year-old girls to attempt murder in 2014. Researchers now study how a fictional entity became a real-world threat — and what it reveals about modern mythology and viral panic.",
    category: "Urban Legends",
    evidenceScore: 88,
    year: "2009",
    wikiTitle: "Slender Man",
  },
  {
    id: "poltergeist-enfield",
    title: "The Enfield Poltergeist",
    slug: "enfield-poltergeist",
    description: "From 1977 to 1978, a north London council house was the scene of furniture movements, knocking, levitation and a child speaking in a gruff adult voice. The case was investigated by the Society for Psychical Research and witnessed by journalists and police.",
    category: "Urban Legends",
    evidenceScore: 29,
    year: "1977",
    wikiTitle: "Enfield poltergeist",
  },
  {
    id: "bigfoot",
    title: "Bigfoot / Sasquatch",
    slug: "bigfoot",
    description: "The legend of a large bipedal hominid in North American forests has persisted for centuries. Native American traditions predate European contact. The 1967 Patterson–Gimlin film remains the most analyzed piece of evidence.",
    category: "Urban Legends",
    evidenceScore: 18,
    wikiTitle: "Bigfoot",
  },
  {
    id: "loch-ness",
    title: "Loch Ness Monster",
    slug: "loch-ness-monster",
    description: "Since the 1930s, hundreds of alleged sightings of a large creature in Scotland's Loch Ness have driven expeditions, sonar surveys, and DNA analysis. A 2023 environmental DNA study found no evidence of a large reptile.",
    category: "Urban Legends",
    evidenceScore: 12,
    year: "1933",
    wikiTitle: "Loch Ness Monster",
  },
  {
    id: "mothman",
    title: "The Mothman",
    slug: "mothman",
    description: "Between November 1966 and December 1967, over 100 residents of Point Pleasant, West Virginia reported a winged humanoid creature. The sightings coincided with the Silver Bridge collapse, killing 46.",
    category: "Urban Legends",
    evidenceScore: 25,
    year: "1966",
    wikiTitle: "Mothman",
  },
  {
    id: "men-in-black",
    title: "Men in Black",
    slug: "men-in-black",
    description: "Since the 1950s, UFO witnesses have reported visits from strange men in black suits who claim to be government agents and warn them to stay silent. The reports are eerily consistent across decades and continents.",
    category: "Urban Legends",
    evidenceScore: 21,
    year: "1947",
    wikiTitle: "Men in black (conspiracy theory)",
  },
  {
    id: "skinwalker-ranch",
    title: "Skinwalker Ranch",
    slug: "skinwalker-ranch",
    description: "A 512-acre Utah property with a 200-year history of paranormal activity: UFO sightings, cattle mutilations, poltergeist phenomena, and electromagnetic anomalies now under a Pentagon-linked investigation.",
    category: "Urban Legends",
    evidenceScore: 31,
    wikiTitle: "Skinwalker Ranch",
  },
  {
    id: "shadow-people",
    title: "Shadow People",
    slug: "shadow-people",
    description: "Accounts of dark, humanoid silhouettes — seen in peripheral vision, standing in doorways, or hovering over sleeping victims — span cultures and centuries. Sleep paralysis explains many encounters, but fully alert witnesses with no history of hallucination continue to report them.",
    category: "Urban Legends",
    evidenceScore: 17,
    wikiTitle: "Shadow person",
  },
  {
    id: "fresno-nightcrawlers",
    title: "Fresno Nightcrawlers",
    slug: "fresno-nightcrawlers",
    description: "In 2007, a Fresno homeowner's security camera captured two pale, featureless figures — appearing to be nothing but long legs — walking across his lawn. A second, near-identical recording appeared in Yosemite in 2011. No explanation has been offered by investigators. Native American traditions from the region describe similar entities.",
    category: "Urban Legends",
    evidenceScore: 22,
    year: "2007",
    wikiTitle: "Fresno Nightcrawlers",
  },
  {
    id: "the-rake",
    title: "The Rake",
    slug: "the-rake",
    description: "Originating from an anonymous 2005 internet post, The Rake describes a pale, naked, hairless humanoid creature that crouches at the foot of beds and watches sleeping people. Unlike most creepypasta, researchers have documented near-identical accounts predating the internet post by decades.",
    category: "Urban Legends",
    evidenceScore: 9,
    year: "2005",
    wikiTitle: "The Rake (creepypasta)",
  },
  {
    id: "max-headroom-hijack",
    title: "Max Headroom Broadcast Hijack",
    slug: "max-headroom-hijack",
    description: "On November 22, 1987, an unknown person wearing a Max Headroom mask hijacked two Chicago television broadcasts, transmitting a bizarre, disturbing 90-second video that was never fully deciphered. The perpetrator was never identified. It remains the only successful broadcast hijacking in US television history.",
    category: "Urban Legends",
    evidenceScore: 94,
    year: "1987",
    wikiTitle: "Max Headroom incident",
  },
  {
    id: "flatwoods-monster",
    title: "The Flatwoods Monster",
    slug: "flatwoods-monster",
    description: "On September 12, 1952, six children and a local woman encountered a 10-foot creature with a red face, glowing eyes, and a hissing spray at the site of a UFO landing in Flatwoods, West Virginia. Several witnesses developed eye and throat irritation. Investigators found skid marks and an oily residue. The creature was never identified.",
    category: "Urban Legends",
    evidenceScore: 34,
    year: "1952",
    wikiTitle: "Flatwoods monster",
  },
  {
    id: "kelly-hopkinsville",
    title: "Kelly-Hopkinsville Encounter",
    slug: "kelly-hopkinsville",
    description: "On August 21, 1955, two families in rural Kentucky reported being besieged all night by small, glowing humanoid creatures with large heads, enormous eyes, and clawed hands. They fired hundreds of rounds at the intruders. Police found bullet holes and deeply shaken witnesses — but no creatures and no physical evidence.",
    category: "Urban Legends",
    evidenceScore: 41,
    year: "1955",
    wikiTitle: "Kelly–Hopkinsville encounter",
  },
  {
    id: "dover-demon",
    title: "The Dover Demon",
    slug: "dover-demon",
    description: "Over two days in April 1977, three separate groups of teenagers in Dover, Massachusetts reported a pale, hairless creature with a large watermelon-shaped head and glowing eyes. Each witness independently drew the same image without having spoken to the others. The sightings have never been explained.",
    category: "Urban Legends",
    evidenceScore: 27,
    year: "1977",
    wikiTitle: "Dover Demon",
  },
  {
    id: "toynbee-tiles",
    title: "The Toynbee Tiles",
    slug: "toynbee-tiles",
    description: "Since the 1980s, cryptic messages have been found embedded in the asphalt of major intersections in Philadelphia, New York, and Washington DC — referencing historian Arnold Toynbee and the resurrection of the dead on Jupiter. Over 130 tiles have been documented. The creator worked in secret for decades. Their identity and purpose remain unknown.",
    category: "Urban Legends",
    evidenceScore: 63,
    year: "1980s",
    wikiTitle: "Toynbee tiles",
  },
  // Debunked
  {
    id: "paul-mccartney-dead",
    title: "Paul McCartney Is Dead",
    slug: "paul-mccartney-dead",
    description: "Since 1966, a persistent theory holds that the real Paul McCartney died in a car crash and was replaced by a lookalike named William Campbell. Believers cite reversed audio, album artwork and song lyrics as clues. Paul McCartney continues to sell out stadiums.",
    category: "Debunked",
    evidenceScore: 2,
    year: "1966",
    wikiTitle: "Paul is dead",
  },
  {
    id: "pyramids-aliens",
    title: "Pyramids Built by Aliens",
    slug: "pyramids-built-by-aliens",
    description: "Archaeologists have found workers' villages, payroll records, tools, graffiti and skeletal remains of pyramid builders. We know who built them, how, and roughly why. The 'aliens built the pyramids' theory erases the extraordinary achievement of thousands of skilled Egyptian workers.",
    category: "Debunked",
    evidenceScore: 2,
    year: "2560 BCE",
    wikiTitle: "Egyptian pyramids",
  },
  {
    id: "moon-landing-hoax",
    title: "Moon Landing Conspiracy",
    slug: "moon-landing-hoax",
    description: "The claim that NASA faked the 1969 Apollo landings has been independently refuted by multiple space agencies, hundreds of thousands of engineers, and retroreflectors still bouncing laser signals from the lunar surface today.",
    category: "Debunked",
    evidenceScore: 3,
    year: "1969",
    wikiTitle: "Moon landing conspiracy theories",
  },
  {
    id: "flat-earth",
    title: "Flat Earth Theory",
    slug: "flat-earth",
    description: "The claim that Earth is a flat disc contradicts GPS, satellite imagery, the physics of gravity, and the observations of every space agency — as well as simple experiments anyone can perform at home.",
    category: "Debunked",
    evidenceScore: 1,
    wikiTitle: "Flat Earth",
  },
  {
    id: "chemtrails",
    title: "Chemtrail Conspiracy",
    slug: "chemtrails",
    description: "The claim that aircraft contrails are chemical agents deliberately sprayed for population control. Atmospheric scientists have repeatedly explained contrail formation physics, and 77 of 77 surveyed experts dismissed the theory.",
    category: "Debunked",
    evidenceScore: 2,
    year: "1990s",
    wikiTitle: "Chemtrail conspiracy theory",
  },
  {
    id: "crop-circles",
    title: "Crop Circles: Alien Messages?",
    slug: "crop-circles",
    description: "From 1991, Doug Bower and Dave Chorley publicly demonstrated they had created hundreds of English crop circles with planks and rope. Despite this, new formations are still widely attributed to extraterrestrial origin.",
    category: "Debunked",
    evidenceScore: 5,
    year: "1978",
    wikiTitle: "Crop circle",
  },
  {
    id: "mandela-effect",
    title: "The Mandela Effect",
    slug: "mandela-effect",
    description: "Millions of people share identical false memories — the Berenstain Bears spelled differently, Nelson Mandela dying in prison, the Monopoly Man's monocle. Skeptics cite confabulation. Others invoke parallel universes. The effect is real; its cause is contested.",
    category: "Debunked",
    evidenceScore: 11,
    year: "2009",
    wikiTitle: "Mandela effect",
  },
  {
    id: "reptilian-elite",
    title: "Reptilian Elite",
    slug: "reptilian-elite",
    description: "David Icke's theory that world leaders are shape-shifting reptilian aliens from the constellation Draco has been comprehensively debunked — yet consistently polls at 4% belief in the US adult population. Its persistence says more about the psychology of conspiracy belief than any evidence.",
    category: "Debunked",
    evidenceScore: 1,
    year: "1998",
    wikiTitle: "Reptilian conspiracy theory",
  },
  {
    id: "birds-arent-real",
    title: "Birds Aren't Real",
    slug: "birds-arent-real",
    description: "A satirical conspiracy theory claiming the US government replaced all birds with surveillance drones between 1959 and 2001. Created in 2017 by Peter McIndoe as performance art, it became a genuine movement — and a serious study in how conspiracies spread and why people adopt them.",
    category: "Debunked",
    evidenceScore: 1,
    year: "2017",
    wikiTitle: "Birds Aren't Real",
  },
  {
    id: "satanic-panic",
    title: "The Satanic Panic",
    slug: "satanic-panic",
    description: "During the 1980s and early 1990s, a wave of Satanic ritual abuse accusations swept the US, UK, and Australia — centred on daycare centres. Hundreds were convicted on uncorroborated testimony from children coached by therapists using now-discredited techniques. Virtually all convictions have been overturned. No physical evidence of Satanic ritual abuse was ever found.",
    category: "Debunked",
    evidenceScore: 4,
    year: "1980",
    wikiTitle: "Satanic panic",
  },
  {
    id: "project-blue-beam",
    title: "Project Blue Beam",
    slug: "project-blue-beam",
    description: "A 1994 theory claiming NASA plans to stage a fake alien invasion using holographic projections to establish a New World Order. Originated with Canadian journalist Serge Monast, who died of a heart attack in 1996 — which believers cite as evidence. The theory has no basis in any declassified document and the technology it describes does not exist.",
    category: "Debunked",
    evidenceScore: 1,
    year: "1994",
    wikiTitle: "Project Blue Beam",
  },
  {
    id: "hollow-earth",
    title: "Hollow Earth Theory",
    slug: "hollow-earth",
    description: "The claim that Earth is hollow and harbours advanced civilisations has been advocated from Edmond Halley to Nazi occultists. Seismic data, satellite gravity mapping, and the physics of planetary formation conclusively establish Earth has a solid iron inner core at 5,200°C. No entrances to a hollow interior have ever been found.",
    category: "Debunked",
    evidenceScore: 1,
    wikiTitle: "Hollow Earth",
  },
  {
    id: "qanon",
    title: "QAnon",
    slug: "qanon",
    description: "Beginning in 2017, anonymous posts claimed a secret cabal of Satan-worshipping paedophiles controlled world governments. Despite every specific prediction failing — including mass arrests and a 'Great Awakening' — the movement grew globally, influenced elections, and directly motivated the January 6, 2021 US Capitol attack.",
    category: "Debunked",
    evidenceScore: 1,
    year: "2017",
    wikiTitle: "QAnon",
  },
];

// ── Curated subsets for the For You feed ─────────────────────────────────────
export const trendingInvestigations: Investigation[] = allInvestigations.filter((i) =>
  ["roswell", "mkultra", "dyatlov", "nazca-lines", "gobekli-tepe", "pentagon-uap"].includes(i.id)
);

export const latestInvestigations: Investigation[] = allInvestigations.filter((i) =>
  ["havana-syndrome", "wow-signal", "skinwalker-ranch", "roanoke"].includes(i.id)
);

export const timelineEvents = [
  { year: "1483", title: "Princes in the Tower", description: "Edward IV's heirs vanish from the Tower of London under Richard III's watch", category: "Historical" },
  { year: "1590", title: "Roanoke Colony", description: "115 colonists disappear. Only the word CROATOAN is left behind", category: "Historical" },
  { year: "1888", title: "Jack the Ripper", description: "Five Whitechapel murders. The killer is never identified", category: "Historical" },
  { year: "1908", title: "Tunguska Event", description: "Something flattens 2,000 km² of Siberian forest — no crater found", category: "Science" },
  { year: "1932", title: "Tuskegee Begins", description: "US government withholds syphilis treatment from 399 Black men for four decades", category: "Government" },
  { year: "1943", title: "MK Ultra Seeds", description: "Operation Paperclip recruits Nazi scientists for US mind-control research", category: "Government" },
  { year: "1947", title: "Roswell Incident", description: "Army announces 'flying disc' recovered — then retracts. Story buried for 30 years", category: "UFO" },
  { year: "1950", title: "Fermi Paradox", description: "Enrico Fermi asks: if the universe is full of life, where is everybody?", category: "Science" },
  { year: "1953", title: "MK Ultra Authorised", description: "CIA Director Dulles signs off on 150+ sub-projects in illegal mind control", category: "Government" },
  { year: "1959", title: "Dyatlov Pass", description: "Nine hikers found dead. Soviet investigators blame 'unknown compelling force'", category: "Unexplained" },
  { year: "1963", title: "JFK Assassinated", description: "Kennedy killed in Dallas. Oswald shot two days later. Files sealed for decades", category: "Government" },
  { year: "1977", title: "The Wow! Signal", description: "Ohio State telescope receives a 72-second broadcast from deep space, never heard again", category: "Science" },
  { year: "1980", title: "Rendlesham Forest", description: "US military personnel encounter a craft in a Suffolk forest. Radiation confirmed", category: "UFO" },
  { year: "1989", title: "Belgian UFO Wave", description: "13,500 witnesses report silent triangular craft. F-16s scrambled, nothing intercepted", category: "UFO" },
  { year: "2004", title: "USS Nimitz Encounter", description: "Navy pilots film Tic-Tac UAP. The footage remains unexplained by the Pentagon", category: "UFO" },
  { year: "2013", title: "Snowden Revelations", description: "NSA mass surveillance of the entire internet confirmed by leaked documents", category: "Government" },
  { year: "2017", title: "'Oumuamua Detected", description: "First interstellar object accelerates out of our solar system without explanation", category: "Science" },
  { year: "2020", title: "Pentagon Confirms UAPs", description: "DoD officially releases Tic-Tac, Gimbal and Go Fast videos as authentic", category: "UFO" },
  { year: "Today", title: "Disclosure Era", description: "Congressional hearings, whistleblowers, and declassification reshape the conversation", category: "Government" },
];

export function getEvidenceLabel(score: number): { label: string; color: string } {
  if (score >= 80) return { label: "Strong Evidence", color: "text-green-400" };
  if (score >= 60) return { label: "Mixed Evidence", color: "text-yellow-400" };
  if (score >= 30) return { label: "Weak Evidence", color: "text-orange-400" };
  return { label: "Unsupported", color: "text-rt-muted" };
}

export function getCategoryColor(category: string): string {
  const map: Record<string, string> = {
    "Government": "bg-blue-900/40 text-blue-300 border-blue-700/40",
    "UFO": "bg-purple-900/40 text-purple-300 border-purple-700/40",
    "Unexplained": "bg-orange-900/40 text-orange-300 border-orange-700/40",
    "Ancient Mysteries": "bg-amber-900/40 text-amber-300 border-amber-700/40",
    "Historical": "bg-stone-800/60 text-stone-300 border-stone-600/40",
    "Science": "bg-cyan-900/40 text-cyan-300 border-cyan-700/40",
    "Urban Legends": "bg-pink-900/40 text-pink-300 border-pink-700/40",
    "Debunked": "bg-emerald-900/40 text-emerald-300 border-emerald-700/40",
  };
  return map[category] ?? "bg-rt-surface text-rt-muted border-rt-border";
}
