export type TimelineEventType =
    | "incident"
    | "leak"
    | "witness"
    | "government"
    | "discovery"
    | "update";

export interface TimelineEntry {
    year: string;
    type: TimelineEventType;
    title: string;
    summary: string;
    source?: string;
    evidenceScore?: number;
}

// Per-investigation timeline data keyed by investigation id
export const investigationTimelines: Record<string, TimelineEntry[]> = {
    "area-51": [
        {
            year: "1947",
            type: "incident",
            title: "Roswell Crash",
            summary: "Reports of a downed object near Roswell, NM redirect military interest toward secret test sites in Nevada.",
            source: "Army Air Force Press Release",
        },
        {
            year: "1951",
            type: "government",
            title: "Site Selection Begins",
            summary: "CIA and USAF surveyors scout remote Nevada dry-lake beds for a classified flight-test facility.",
            source: "CIA Declassified Files, 2013",
        },
        {
            year: "1955",
            type: "government",
            title: "Groom Lake Activated",
            summary: "Area 51 officially established as a test site for the Lockheed U-2 high-altitude reconnaissance aircraft.",
            source: "CIA History Staff, 1998",
            evidenceScore: 95,
        },
        {
            year: "1957",
            type: "discovery",
            title: "U-2 Overflights of USSR",
            summary: "Spy planes launching from Area 51 photograph Soviet nuclear facilities — triggering a wave of UFO reports from confused airline pilots.",
            source: "NSA Declassified Archive",
            evidenceScore: 98,
        },
        {
            year: "1960",
            type: "incident",
            title: "Gary Powers Shot Down",
            summary: "A U-2 is downed over the USSR, forcing Eisenhower to publicly admit the spy program — partially exposing Area 51.",
            source: "CIA Inspector General Report",
            evidenceScore: 99,
        },
        {
            year: "1964",
            type: "discovery",
            title: "A-12 OXCART Testing",
            summary: "The Mach-3 A-12 OXCART — predecessor to the SR-71 — is tested secretly. Its speed and shape generate hundreds of new UFO sightings.",
            source: "Declassified USAF Records",
            evidenceScore: 95,
        },
        {
            year: "1989",
            type: "witness",
            title: "Bob Lazar Comes Forward",
            summary: "Physicist Bob Lazar claims he reverse-engineered alien propulsion systems at 'S-4', a sub-site near Area 51. Some credentials later confirmed.",
            source: "KLAS-TV Las Vegas Broadcast",
            evidenceScore: 28,
        },
        {
            year: "1995",
            type: "government",
            title: "CIA Acknowledges Existence",
            summary: "For the first time, the CIA officially admits Area 51 exists in a declassified document, though details remain redacted.",
            source: "CIA Freedom of Information Act Release",
            evidenceScore: 100,
        },
        {
            year: "2013",
            type: "leak",
            title: "400-Page History Released",
            summary: "NSA releases comprehensive history of Area 51's U-2 and A-12 programs, confirming decades of covert aviation development.",
            source: "National Security Archive",
            evidenceScore: 100,
        },
        {
            year: "Today",
            type: "update",
            title: "UAP Congressional Hearings",
            summary: "US Congress holds public and classified hearings on Unidentified Aerial Phenomena. Former pilots and intelligence officers testify. Many questions remain.",
            source: "House Armed Services Committee, 2024",
            evidenceScore: 74,
        },
    ],

    "roswell": [
        {
            year: "Jul 1947",
            type: "incident",
            title: "Something Falls Near Roswell",
            summary: "Ranch manager Mac Brazel discovers large quantities of unusual debris scattered across a remote field. He notifies local sheriff.",
            source: "Roswell Daily Record",
        },
        {
            year: "Jul 8, 1947",
            type: "government",
            title: "Army Announces 'Flying Disc'",
            summary: "Roswell Army Air Field public information officer Walter Haut issues a press release confirming capture of a 'flying disc'. The world goes wild.",
            source: "RAAF Press Release",
            evidenceScore: 99,
        },
        {
            year: "Jul 9, 1947",
            type: "government",
            title: "Retraction: 'Weather Balloon'",
            summary: "General Roger Ramey holds a press conference calling the debris a weather balloon. The story is officially dead — for 30 years.",
            source: "Fort Worth Army Air Field Statement",
            evidenceScore: 99,
        },
        {
            year: "1978",
            type: "witness",
            title: "Stanton Friedman Investigation",
            summary: "Nuclear physicist Stanton Friedman tracks down former intelligence officer Jesse Marcel, who says the debris was 'not of this world'.",
            source: "National Enquirer Interview",
            evidenceScore: 42,
        },
        {
            year: "1994",
            type: "government",
            title: "Air Force Report: Project Mogul",
            summary: "The USAF declassifies files attributing Roswell debris to Project Mogul — classified balloon trains monitoring Soviet nuclear tests.",
            source: "USAF Report, 1994",
            evidenceScore: 85,
        },
        {
            year: "1997",
            type: "update",
            title: "50th Anniversary Investigation",
            summary: "CNN, NBC and international media descend on Roswell. A second Air Force report addresses 'alien bodies' claims — attributing them to crash test dummies.",
            source: "USAF Case Closed Report, 1997",
        },
        {
            year: "Today",
            type: "update",
            title: "Declassification Continues",
            summary: "UAP disclosure acts passed by Congress. Roswell remains the defining origin point of modern UFO culture and government secrecy debates.",
            source: "UAP Disclosure Act, 2023",
            evidenceScore: 68,
        },
    ],

    "mkultra": [
        {
            year: "1945",
            type: "government",
            title: "Operation Paperclip Seeds",
            summary: "Nazi scientists with mind-control research backgrounds are recruited by US intelligence, laying groundwork for future programs.",
            source: "OSS Archives",
            evidenceScore: 95,
        },
        {
            year: "1950",
            type: "government",
            title: "Project ARTICHOKE",
            summary: "CIA begins experimenting with hypnosis, forced morphine addiction and LSD as interrogation tools on unwitting prisoners.",
            source: "Church Committee Report",
            evidenceScore: 99,
        },
        {
            year: "1953",
            type: "government",
            title: "MK Ultra Officially Authorised",
            summary: "CIA Director Allen Dulles formally approves Project MK Ultra — 150+ sub-projects across 80 institutions, most kept secret from subjects.",
            source: "CIA Director Memo, April 1953",
            evidenceScore: 100,
        },
        {
            year: "1953",
            type: "incident",
            title: "Frank Olson Dies",
            summary: "CIA scientist Frank Olson falls from a New York hotel window 9 days after being dosed with LSD without consent. Death ruled suicide.",
            source: "New York Medical Examiner",
            evidenceScore: 91,
        },
        {
            year: "1973",
            type: "leak",
            title: "Director Orders Files Destroyed",
            summary: "CIA Director Richard Helms orders all MK Ultra records destroyed ahead of Watergate investigations. Most documents are shredded.",
            source: "Senate Intelligence Committee",
            evidenceScore: 99,
        },
        {
            year: "1977",
            type: "discovery",
            title: "7,000 Documents Survive",
            summary: "A FOIA request uncovers 7,000 misfiled MK Ultra documents in a financial records room. The scandal becomes public.",
            source: "Senate Subcommittee Hearings, 1977",
            evidenceScore: 100,
        },
        {
            year: "1995",
            type: "government",
            title: "Presidential Apology",
            summary: "President Clinton publicly apologises to surviving victims of government-sponsored human radiation experiments, many linked to MK Ultra.",
            source: "White House Statement, 1995",
            evidenceScore: 100,
        },
        {
            year: "Today",
            type: "update",
            title: "Ongoing Declassification",
            summary: "Researchers continue to uncover sub-projects. The full scope of MK Ultra is still unknown — an estimated 20% of documents survived destruction.",
            evidenceScore: 91,
        },
    ],

    "jfk": [
        {
            year: "Nov 22, 1963",
            type: "incident",
            title: "Assassination in Dallas",
            summary: "President Kennedy is shot in Dealey Plaza. Texas Governor Connally is also wounded. Lee Harvey Oswald is arrested hours later.",
            source: "Dallas Police Department",
            evidenceScore: 100,
        },
        {
            year: "Nov 24, 1963",
            type: "incident",
            title: "Oswald Shot Live on TV",
            summary: "Jack Ruby shoots Lee Harvey Oswald in the Dallas police basement — witnessed by millions on live television.",
            source: "NBC News Broadcast",
            evidenceScore: 100,
        },
        {
            year: "1964",
            type: "government",
            title: "Warren Commission: Lone Gunman",
            summary: "The Warren Commission concludes a single shooter — Lee Harvey Oswald — was solely responsible. The 'magic bullet' theory is introduced.",
            source: "Warren Commission Report",
            evidenceScore: 71,
        },
        {
            year: "1979",
            type: "government",
            title: "House Select Committee: Conspiracy",
            summary: "A second investigation concludes Kennedy was 'probably assassinated as a result of a conspiracy', based on acoustic evidence.",
            source: "HSCA Final Report",
            evidenceScore: 71,
        },
        {
            year: "1991",
            type: "update",
            title: "Oliver Stone's JFK Released",
            summary: "The film sparks public outcry, directly leading Congress to pass the JFK Records Collection Act — forcing document release.",
            source: "JFK Records Act, 1992",
        },
        {
            year: "2017–2023",
            type: "leak",
            title: "Batch Declassifications",
            summary: "Trump and Biden administrations release over 15,000 previously secret CIA and FBI documents. Key files still redacted until 2039.",
            source: "National Archives",
            evidenceScore: 71,
        },
        {
            year: "Today",
            type: "update",
            title: "Final Files Still Withheld",
            summary: "Despite legal deadlines, hundreds of documents remain classified. Intelligence agencies cite ongoing 'national security' concerns.",
            source: "NARA Status Report, 2024",
            evidenceScore: 71,
        },
    ],

    "dyatlov-pass": [
        {
            year: "Jan 1959",
            type: "incident",
            title: "Group Sets Off",
            summary: "10 experienced hikers led by Igor Dyatlov begin their trek through the Ural Mountains toward Otorten peak. One turns back due to illness.",
            source: "Ural Polytechnic Institute Records",
        },
        {
            year: "Feb 1, 1959",
            type: "incident",
            title: "Last Known Camp",
            summary: "The group's last diary entries and photographs show them setting up camp on the slope of Dead Mountain. Nothing unusual is noted.",
            source: "Recovered Diaries",
            evidenceScore: 99,
        },
        {
            year: "Feb 26, 1959",
            type: "discovery",
            title: "Search Party Finds Empty Tent",
            summary: "Rescuers find the tent cut open from inside. Nine sets of footprints lead into the snow — some barefoot. No sign of the hikers.",
            source: "Soviet Search Party Report",
            evidenceScore: 99,
        },
        {
            year: "Mar 1959",
            type: "discovery",
            title: "Bodies Found",
            summary: "Five bodies recovered near the forest. No external injuries. Cause of death: hypothermia. Three had fled the tent in their underwear.",
            source: "Soviet Medical Examiner",
            evidenceScore: 99,
        },
        {
            year: "May 1959",
            type: "discovery",
            title: "Four More Bodies — Severe Injuries",
            summary: "The final four are found buried under snow. Massive internal injuries: crushed ribs, fractured skull — yet no external wounds. One is missing her tongue.",
            source: "Soviet Forensic Report",
            evidenceScore: 99,
        },
        {
            year: "1959",
            type: "government",
            title: "Case Closed: 'Unknown Force'",
            summary: "Soviet investigators officially attribute the deaths to an 'unknown compelling force'. Files are sealed for 30 years.",
            source: "Soviet Prosecutor's Office",
        },
        {
            year: "2019",
            type: "government",
            title: "Russia Reopens Investigation",
            summary: "Russian prosecutors reopen the case. Their conclusion: the group was killed by an avalanche. Many experts dispute this explanation.",
            source: "Russian Prosecutor General",
            evidenceScore: 55,
        },
        {
            year: "Today",
            type: "update",
            title: "Debate Continues",
            summary: "Researchers propose infrasound, katabatic wind events, and military testing. The case remains officially unsolved to many.",
            evidenceScore: 55,
        },
    ],

    "philadelphia-experiment": [
        {
            year: "1943",
            type: "incident",
            title: "USS Eldridge in Service",
            summary: "The destroyer escort USS Eldridge is commissioned. According to later claims, it becomes the subject of a classified Navy invisibility experiment.",
            source: "Naval Records",
        },
        {
            year: "1956",
            type: "witness",
            title: "Carlos Allende's Letters",
            summary: "A man named Carlos Allende mails annotated copies of Morris Jessup's UFO book to the Navy, claiming to have witnessed the experiment firsthand.",
            source: "ONR Records",
            evidenceScore: 12,
        },
        {
            year: "1979",
            type: "discovery",
            title: "Story Goes Mainstream",
            summary: "Charles Berlitz and William Moore publish 'The Philadelphia Experiment', bringing the story to mass audiences.",
            source: "Published Book",
            evidenceScore: 22,
        },
        {
            year: "1984",
            type: "witness",
            title: "Al Bielek Claims",
            summary: "Man claiming to be 'Ed Cameron' says he was aboard the Eldridge and teleported to 1983. Claim widely disputed.",
            source: "Lecture Circuit",
            evidenceScore: 5,
        },
        {
            year: "1999",
            type: "government",
            title: "Navy Denies Everything",
            summary: "Navy releases official statement and ship logs. The USS Eldridge was not in Philadelphia on the alleged dates — it was in the Bahamas.",
            source: "US Navy Official Statement",
            evidenceScore: 99,
        },
        {
            year: "Today",
            type: "update",
            title: "Classified Degaussing Programs",
            summary: "Researchers point to real classified Navy degaussing (demagnetisation) experiments that may have inspired the legend.",
            source: "Naval History & Heritage Command",
            evidenceScore: 22,
        },
    ],

    "pentagon-uap": [
        {
            year: "2004",
            type: "incident",
            title: "USS Nimitz Encounter",
            summary: "Navy pilots encounter a white Tic-Tac shaped object off San Diego. It performs manoeuvres impossible for known aircraft. Video is recorded.",
            source: "US Navy Pilot Testimony",
            evidenceScore: 92,
        },
        {
            year: "2007",
            type: "government",
            title: "AATIP Program Begins",
            summary: "Pentagon secretly funds the Advanced Aerospace Threat Identification Program to investigate UAP reports. Budget: $22 million.",
            source: "Pentagon Budget Documents",
            evidenceScore: 95,
        },
        {
            year: "2017",
            type: "leak",
            title: "New York Times Exposé",
            summary: "The New York Times breaks the story of AATIP's existence. The Tic-Tac, Gimbal and Go Fast videos leak to the public.",
            source: "New York Times, Dec 2017",
            evidenceScore: 99,
        },
        {
            year: "2020",
            type: "government",
            title: "Pentagon Officially Releases Videos",
            summary: "The Department of Defense officially releases the three UAP videos and acknowledges they show 'unidentified aerial phenomena'.",
            source: "DoD Press Release, April 2020",
            evidenceScore: 100,
        },
        {
            year: "2021",
            type: "government",
            title: "ODNI Preliminary Assessment",
            summary: "Intelligence report on 144 UAP incidents confirms: 143 remain unexplained. One attributed to deflating balloon.",
            source: "ODNI Preliminary Assessment",
            evidenceScore: 95,
        },
        {
            year: "2023",
            type: "witness",
            title: "Grusch Whistleblower Testimony",
            summary: "Former intelligence official David Grusch testifies to Congress that the US has retrieved 'non-human' craft and biologics. Claims denied by DoD.",
            source: "House Oversight Committee Hearing, 2023",
            evidenceScore: 60,
        },
        {
            year: "Today",
            type: "update",
            title: "UAP Disclosure Act",
            summary: "Congress passes legislation requiring mandatory declassification of UAP-related government records over the next 25 years.",
            source: "UAP Disclosure Act, 2023",
            evidenceScore: 79,
        },
    ],

    "tunguska": [
        {
            year: "Jun 30, 1908",
            type: "incident",
            title: "The Explosion",
            summary: "At 7:17 AM local time, a fireball blazes across the Siberian sky and detonates approximately 8–10 km above the Podkamennaya Tunguska River. The blast — estimated at 10–15 megatons — flattens 2,150 km² of forest and is heard 1,000 km away.",
            source: "Russian Academy of Sciences",
            evidenceScore: 99,
        },
        {
            year: "1908",
            type: "witness",
            title: "Eyewitness Accounts",
            summary: "Hundreds of Evenki people and settlers report a pillar of bluish light as bright as the sun, followed by a flash and a sound like artillery fire. Many are knocked off their feet. No crater is found.",
            source: "Siberian Expedition Reports",
            evidenceScore: 97,
        },
        {
            year: "1921",
            type: "discovery",
            title: "First Scientific Expedition",
            summary: "Leonid Kulik leads the first Soviet expedition toward the blast site. Poor maps and hostile terrain prevent him from reaching the epicentre.",
            source: "Soviet Academy of Sciences",
        },
        {
            year: "1927",
            type: "discovery",
            title: "Kulik Reaches Ground Zero",
            summary: "Kulik finally reaches the epicentre. He finds 80 million trees flattened radially across an 80 km diameter — but no crater and no meteorite fragments.",
            source: "Kulik Expedition Report, 1927",
            evidenceScore: 99,
        },
        {
            year: "1958",
            type: "discovery",
            title: "Microscopic Silicate Spheres Found",
            summary: "Soviet scientists recover microscopic magnetite and silicate spheres consistent with a vaporised cosmic body — confirming an extraterrestrial origin.",
            source: "Florensky, Soviet Academy of Sciences",
            evidenceScore: 91,
        },
        {
            year: "2013",
            type: "incident",
            title: "Chelyabinsk Airburst",
            summary: "A 20-metre asteroid explodes over Chelyabinsk, Russia, injuring 1,500 people — the first comparable airburst since Tunguska and a stark reminder of the ongoing threat.",
            source: "NASA Jet Propulsion Laboratory",
            evidenceScore: 100,
        },
        {
            year: "Today",
            type: "update",
            title: "Comet vs Asteroid Still Debated",
            summary: "Most scientists favour a stony asteroid that vaporised on impact. A 2013 study found a lake fragment matching the trajectory. No single explanation has achieved full consensus.",
            source: "Planetary and Space Science Journal",
            evidenceScore: 71,
        },
    ],

    "wow-signal": [
        {
            year: "Aug 15, 1977",
            type: "incident",
            title: "The Signal Is Received",
            summary: "Astronomer Jerry Ehman, reviewing data from Ohio State's Big Ear radio telescope, circles a 72-second narrowband transmission on a printout and writes 'Wow!' in the margin. It matches every predicted characteristic of an interstellar signal.",
            source: "Big Ear Radio Observatory, OSU",
            evidenceScore: 99,
        },
        {
            year: "1977",
            type: "discovery",
            title: "Signal Characteristics Analysed",
            summary: "The signal arrived at 1420 MHz — the hydrogen line, long theorised as the universal frequency for interstellar communication. Its intensity was 30 times stronger than background noise.",
            source: "NAAPO Technical Report",
            evidenceScore: 98,
        },
        {
            year: "1978–1987",
            type: "government",
            title: "Hundreds of Follow-Up Searches Fail",
            summary: "Big Ear and telescopes worldwide attempt to re-detect the signal over a decade of targeted searches. It is never heard again.",
            source: "SETI Institute Archives",
            evidenceScore: 99,
        },
        {
            year: "1994",
            type: "update",
            title: "Big Ear Demolished",
            summary: "Ohio State University demolishes Big Ear Radio Observatory to build a golf course, ending the longest continuous SETI survey in history.",
            source: "NAAPO Records",
        },
        {
            year: "2012",
            type: "update",
            title: "Response Broadcast: 'A Message From Earth'",
            summary: "On the 35th anniversary, a message from 10,000 people is broadcast toward the Wow! signal's origin using a Ukrainian radio telescope.",
            source: "National Geographic / Arecibo",
        },
        {
            year: "2017",
            type: "discovery",
            title: "Cometary Hydrogen Cloud Theory",
            summary: "Astronomer Antonio Paris proposes two hydrogen-emitting comets passed through the beam at the right time. The explanation is disputed — critics note the comets' sky position does not match.",
            source: "Journal of the Washington Academy of Sciences",
            evidenceScore: 31,
        },
        {
            year: "Today",
            type: "update",
            title: "Origin Unresolved",
            summary: "No natural or artificial explanation has been accepted by the majority of researchers. The Wow! signal remains the strongest candidate for extraterrestrial radio contact ever detected.",
            evidenceScore: 84,
        },
    ],

    "dyatlov": [
        {
            year: "Jan 1959",
            type: "incident",
            title: "Group Sets Off",
            summary: "10 experienced hikers led by Igor Dyatlov begin their trek through the Ural Mountains toward Otorten peak. One turns back due to illness.",
            source: "Ural Polytechnic Institute Records",
        },
        {
            year: "Feb 1, 1959",
            type: "incident",
            title: "Last Known Camp",
            summary: "The group's last diary entries and photographs show them setting up camp on the slope of Dead Mountain. Nothing unusual is noted.",
            source: "Recovered Diaries",
            evidenceScore: 99,
        },
        {
            year: "Feb 26, 1959",
            type: "discovery",
            title: "Search Party Finds Empty Tent",
            summary: "Rescuers find the tent slashed open from inside. Nine sets of footprints lead downhill into the snow — some barefoot. No sign of the hikers.",
            source: "Soviet Search Party Report",
            evidenceScore: 99,
        },
        {
            year: "Mar 1959",
            type: "discovery",
            title: "First Five Bodies Found",
            summary: "Five bodies recovered near the treeline. No external injuries. Cause of death: hypothermia. Three had fled the tent in their underwear.",
            source: "Soviet Medical Examiner",
            evidenceScore: 99,
        },
        {
            year: "May 1959",
            type: "discovery",
            title: "Four More Bodies — Severe Trauma",
            summary: "The final four are found under four metres of snow in a ravine. Massive internal injuries: crushed ribs, fractured skull — yet no external wounds. One is missing her tongue.",
            source: "Soviet Forensic Report",
            evidenceScore: 99,
        },
        {
            year: "1959",
            type: "government",
            title: "Case Closed: 'Unknown Compelling Force'",
            summary: "Soviet investigators attribute the deaths to an 'unknown compelling force of nature'. All files are sealed for 30 years.",
            source: "Soviet Prosecutor's Office",
        },
        {
            year: "2019",
            type: "government",
            title: "Russia Reopens the Case",
            summary: "Russian prosecutors reopen the investigation. Their official conclusion: the group was killed by a slab avalanche. Many independent researchers and avalanche experts dispute this.",
            source: "Russian Prosecutor General",
            evidenceScore: 55,
        },
        {
            year: "Today",
            type: "update",
            title: "Debate Continues",
            summary: "Competing theories include infrasound panic, a katabatic wind event, secret military testing, and paradoxical undressing during hypothermia. No single explanation accounts for all evidence.",
            evidenceScore: 55,
        },
    ],

    "bermuda-triangle": [
        {
            year: "Dec 5, 1945",
            type: "incident",
            title: "Flight 19 Vanishes",
            summary: "Five US Navy TBF Avenger torpedo bombers on a training flight out of Fort Lauderdale disappear over the Atlantic. The last radio transmission reports the pilots are 'completely lost'. A rescue PBM Mariner sent to find them also vanishes — 27 men total.",
            source: "US Navy Board of Investigation",
            evidenceScore: 99,
        },
        {
            year: "1952",
            type: "witness",
            title: "George Sand's Article",
            summary: "Fate magazine publishes 'Sea Mystery at Our Back Door' — the first article to catalogue a pattern of disappearances in a loosely defined Atlantic triangle.",
            source: "Fate Magazine",
        },
        {
            year: "1964",
            type: "discovery",
            title: "The Triangle Is Named",
            summary: "Vincent Gaddis coins 'the Bermuda Triangle' in Argosy magazine, crystallising the region into a defined cultural phenomenon.",
            source: "Argosy Magazine",
        },
        {
            year: "1974",
            type: "witness",
            title: "Charles Berlitz's Best-Seller",
            summary: "'The Bermuda Triangle' sells 20 million copies worldwide and cements the legend, attributing disappearances to Atlantis, aliens, and time warps.",
            source: "Published Book",
            evidenceScore: 18,
        },
        {
            year: "1975",
            type: "discovery",
            title: "Lawrence Kusche's Rebuttal",
            summary: "Researcher Lawrence Kusche publishes 'The Bermuda Triangle Mystery — Solved', showing most cited incidents involved distorted facts, wrong dates, or ships outside the Triangle.",
            source: "Harper & Row",
            evidenceScore: 88,
        },
        {
            year: "2013",
            type: "discovery",
            title: "Flight 19 Partial Wreckage Found?",
            summary: "Researchers announce discovery of a TBF Avenger off Fort Lauderdale, potentially from Flight 19. The Navy has not confirmed a match.",
            source: "Deep Sea Vision / News Reports",
            evidenceScore: 42,
        },
        {
            year: "Today",
            type: "update",
            title: "Statistically Unremarkable",
            summary: "Lloyd's of London and the US Coast Guard confirm the Bermuda Triangle has no higher rate of disappearances than other heavily-trafficked ocean regions. Most losses are attributable to weather and human error.",
            source: "Lloyd's of London; USCG",
            evidenceScore: 93,
        },
    ],

    "voynich": [
        {
            year: "1404–1438",
            type: "incident",
            title: "Manuscript Created",
            summary: "Radiocarbon dating places the vellum's creation in the early 15th century. The manuscript contains 240 pages of dense, flowing text in an unknown script, illustrated with botanical, astronomical, and biological drawings found nowhere else.",
            source: "University of Arizona Carbon Dating, 2009",
            evidenceScore: 97,
        },
        {
            year: "1586",
            type: "discovery",
            title: "Emperor Rudolf II Purchases It",
            summary: "Holy Roman Emperor Rudolf II allegedly purchases the manuscript for 600 gold ducats — the equivalent of a modest estate — suggesting someone believed it was extraordinarily valuable.",
            source: "Marci Letter, 1665",
            evidenceScore: 71,
        },
        {
            year: "1912",
            type: "discovery",
            title: "Wilfrid Voynich Acquires It",
            summary: "Polish-American antiquarian Wilfrid Voynich purchases the manuscript from the Jesuit Villa Mondragone in Italy, bringing it to international attention.",
            source: "Voynich Personal Papers",
        },
        {
            year: "1944",
            type: "government",
            title: "NSA Cryptanalysts Fail",
            summary: "During and after WWII, professional codebreakers including NSA analysts attempt to crack the Voynich script. All fail. The NSA's classified report is not declassified until 2002.",
            source: "NSA Technical Journal, Declassified 2002",
            evidenceScore: 99,
        },
        {
            year: "2004",
            type: "discovery",
            title: "Statistical Language Analysis",
            summary: "Computer analysis confirms Voynich text follows Zipf's law and has real internal structure — ruling out random gibberish and supporting a genuine encoded language.",
            source: "Computational Linguistics Studies",
            evidenceScore: 82,
        },
        {
            year: "2019",
            type: "witness",
            title: "'Decoded' — Then Refuted",
            summary: "A UK academic claims to translate the manuscript as a women's health guide in proto-Romance language. The claim is swiftly rejected by medieval linguists.",
            source: "Times Higher Education",
            evidenceScore: 8,
        },
        {
            year: "Today",
            type: "update",
            title: "Still Undeciphered",
            summary: "The Voynich Manuscript remains the world's most famous undeciphered text, held at Yale's Beinecke Library. AI and deep-learning attempts continue. No consensus solution exists.",
            source: "Beinecke Rare Book Library, Yale",
            evidenceScore: 99,
        },
    ],

    "db-cooper": [
        {
            year: "Nov 24, 1971",
            type: "incident",
            title: "The Hijacking",
            summary: "A man calling himself Dan Cooper boards Northwest Orient Flight 305 from Portland to Seattle. He hands a stewardess a note claiming he has a bomb, demands $200,000 in cash and four parachutes.",
            source: "FBI Case File",
            evidenceScore: 99,
        },
        {
            year: "Nov 24, 1971",
            type: "incident",
            title: "The Jump",
            summary: "With the ransom delivered, Cooper sends passengers home at Seattle-Tacoma airport, keeps four crew members, and orders the plane south toward Mexico City. Somewhere over southwest Washington, he lowers the rear stairs and jumps into the night in a rainstorm.",
            source: "FAA / FBI Investigation",
            evidenceScore: 99,
        },
        {
            year: "1972–1976",
            type: "government",
            title: "Operation NORJAK",
            summary: "The FBI launches its largest case, dubbed NORJAK (Northwest Hijacking). Over 800 suspects are investigated. None are charged. All parachutes are accounted for except two.",
            source: "FBI NORJAK File",
            evidenceScore: 99,
        },
        {
            year: "1980",
            type: "discovery",
            title: "Ransom Bills Found",
            summary: "Eight-year-old Brian Ingram discovers a rotting bundle of $20 bills on the bank of the Columbia River. Serial numbers confirm they are Cooper's ransom money — but only $5,800 of $200,000.",
            source: "FBI Laboratory Analysis",
            evidenceScore: 95,
        },
        {
            year: "2007",
            type: "discovery",
            title: "Partial DNA Profile Obtained",
            summary: "The FBI recovers a partial DNA profile from Cooper's clip-on tie, left on the plane. No match found in any database.",
            source: "FBI Press Release, 2007",
            evidenceScore: 71,
        },
        {
            year: "2016",
            type: "government",
            title: "FBI Suspends Active Investigation",
            summary: "After 45 years, the FBI announces it is suspending active investigation to focus resources elsewhere. The case file remains open.",
            source: "FBI Press Release, July 2016",
            evidenceScore: 99,
        },
        {
            year: "Today",
            type: "update",
            title: "Identity Unknown",
            summary: "D.B. Cooper remains the only unsolved case of air piracy in US commercial aviation history. Citizen investigators continue analysing suspects. No confirmed identity.",
            evidenceScore: 84,
        },
    ],

    "rendlesham": [
        {
            year: "Dec 26, 1980",
            type: "incident",
            title: "First Night: Lights in Rendlesham Forest",
            summary: "USAF security personnel at RAF Bentwaters investigate unusual lights in Rendlesham Forest. Airman John Burroughs approaches a glowing triangular craft resting on the forest floor. It silently departs.",
            source: "USAF Security Police Report",
            evidenceScore: 91,
        },
        {
            year: "Dec 28, 1980",
            type: "incident",
            title: "Second Night: Landing Marks Found",
            summary: "Deputy Base Commander Lieutenant Colonel Charles Halt leads a patrol back to the site. They find triangular indentations in the ground and radiation readings significantly above background levels.",
            source: "Halt Memo, 1981",
            evidenceScore: 88,
        },
        {
            year: "Dec 28, 1980",
            type: "witness",
            title: "Halt's Audio Recording",
            summary: "Halt records the encounter live on a handheld cassette recorder. The 18-minute tape — later released — captures officers describing a pulsing light that beams a shaft of energy at their feet.",
            source: "Halt Audio Tape",
            evidenceScore: 91,
        },
        {
            year: "Jan 13, 1981",
            type: "government",
            title: "The Halt Memo",
            summary: "Halt sends a memo to the UK Ministry of Defence summarising events. The memo is later released under FOIA. Its understatement ('unexplained lights') becomes iconic.",
            source: "MoD FOIA Release",
            evidenceScore: 99,
        },
        {
            year: "1983",
            type: "leak",
            title: "First Public Disclosure",
            summary: "Investigator Barry Greenwood obtains the Halt memo via FOIA. The story breaks in the News of the World. NATO suppression allegations begin.",
            source: "News of the World",
        },
        {
            year: "2010",
            type: "witness",
            title: "Halt Calls for Disclosure",
            summary: "Charles Halt signs an affidavit formally requesting the US and UK governments disclose what they know about Rendlesham, stating he believes the craft was extraterrestrial.",
            source: "Halt Affidavit, 2010",
            evidenceScore: 71,
        },
        {
            year: "Today",
            type: "update",
            title: "Europe's Most Documented UFO Case",
            summary: "Rendlesham remains the best-documented UFO case in European history. Official explanations — a lighthouse, misidentified Soviet satellite — are rejected by most witnesses. MoD files remain partly classified.",
            evidenceScore: 84,
        },
    ],

    "zodiac": [
        {
            year: "Dec 20, 1968",
            type: "incident",
            title: "First Confirmed Attack",
            summary: "Two teenagers are shot while parked at Lake Herman Road in Benicia, California. Betty Lou Jensen dies at the scene; David Faraday dies en route to hospital.",
            source: "Solano County Sheriff's Report",
            evidenceScore: 99,
        },
        {
            year: "Jul 4, 1969",
            type: "incident",
            title: "Blue Rock Springs Attack",
            summary: "Darlene Ferrin and Michael Mageau are shot at Blue Rock Springs Park in Vallejo. Ferrin dies; Mageau survives. An anonymous caller to Vallejo PD claims responsibility for both attacks.",
            source: "Vallejo Police Department",
            evidenceScore: 99,
        },
        {
            year: "Aug 1, 1969",
            type: "leak",
            title: "Three Newspapers Receive Ciphers",
            summary: "The San Francisco Chronicle, San Francisco Examiner, and Vallejo Times-Herald receive identical letters from the Zodiac — each containing one-third of a 408-symbol cipher and a demand for front-page publication.",
            source: "San Francisco Chronicle",
            evidenceScore: 99,
        },
        {
            year: "Aug 8, 1969",
            type: "discovery",
            title: "First Cipher Decoded",
            summary: "High school teachers Donald and Bettye Harden crack the 408-cipher in a weekend. It reads: 'I like killing people because it is so much fun.'",
            source: "FBI Cryptanalysis Division",
            evidenceScore: 99,
        },
        {
            year: "1969–1974",
            type: "incident",
            title: "Confirmed Murders: Five",
            summary: "Law enforcement confirm five Zodiac murders across Solano and San Francisco counties. The killer claims 37 victims in letters; the true count is unknown.",
            source: "SFPD / FBI Case File",
            evidenceScore: 99,
        },
        {
            year: "Dec 2020",
            type: "discovery",
            title: "Z-340 Cipher Cracked — 51 Years Later",
            summary: "A team of amateur codebreakers crack the 340-character cipher sent in 1969. It reads in part: 'I hope you are having lots of fun in trying to catch me.'",
            source: "FBI Confirmed, Dec 11 2020",
            evidenceScore: 99,
        },
        {
            year: "Today",
            type: "update",
            title: "Identity Unknown",
            summary: "Despite DNA evidence, hundreds of suspects, and a partial fingerprint, the Zodiac's identity has never been confirmed. The case remains officially open.",
            evidenceScore: 84,
        },
    ],

    "mkultra-cameron": [
        {
            year: "1945",
            type: "government",
            title: "Rockefeller Grant for 'Psychic Driving'",
            summary: "Dr. Ewen Cameron begins experimenting with repeated audio messages as a tool for 'reprogramming' patients at McGill University's Allan Memorial Institute.",
            source: "McGill University Records",
            evidenceScore: 88,
        },
        {
            year: "1957",
            type: "government",
            title: "CIA Funding Begins",
            summary: "The CIA begins covertly funding Cameron's research through a front organisation — the Society for the Investigation of Human Ecology — without his patients' knowledge or consent.",
            source: "Church Committee Report",
            evidenceScore: 97,
        },
        {
            year: "1957–1964",
            type: "incident",
            title: "The Experiments",
            summary: "Patients seeking treatment for depression and anxiety are subjected to weeks of drug-induced sleep, ECT at 30–40 times normal intensity, sensory deprivation, and looped audio messages. Many suffer permanent memory loss and personality destruction.",
            source: "Senate Subcommittee Hearings",
            evidenceScore: 99,
        },
        {
            year: "1977",
            type: "leak",
            title: "MK Ultra Documents Expose Cameron",
            summary: "The surviving 7,000 MK Ultra documents obtained by FOIA reveal Cameron's involvement. The Canadian government and CIA had concealed the programme from Canadians.",
            source: "Senate FOIA Release",
            evidenceScore: 99,
        },
        {
            year: "1984",
            type: "government",
            title: "US Victims Settle",
            summary: "Nine Canadian survivors sue the CIA. The CIA settles out of court for $750,000, admitting no liability.",
            source: "US District Court Settlement",
            evidenceScore: 99,
        },
        {
            year: "1992",
            type: "government",
            title: "Canada Pays Compensation",
            summary: "The Canadian government pays $100,000 to each of 77 surviving victims — acknowledging that McGill and the Canadian government funded Cameron's experiments alongside the CIA.",
            source: "Canadian Government Statement",
            evidenceScore: 99,
        },
        {
            year: "Today",
            type: "update",
            title: "Legacy of Trauma",
            summary: "Many second-generation families report inherited trauma. Cameron's experiments are cited in legal frameworks for informed consent and still inform debates on state-sponsored torture.",
            evidenceScore: 97,
        },
    ],

    "operation-mockingbird": [
        {
            year: "1947",
            type: "government",
            title: "Office of Policy Coordination",
            summary: "The CIA establishes the Office of Policy Coordination under Frank Wisner, tasked with covert influence operations including control of US media narratives.",
            source: "CIA Historical Review Program",
            evidenceScore: 91,
        },
        {
            year: "1950",
            type: "government",
            title: "Programme Expands",
            summary: "Under CIA officer Cord Meyer, the programme recruits journalists at major US outlets including the Washington Post, Time magazine, and CBS to publish stories aligned with US intelligence objectives.",
            source: "Church Committee Report",
            evidenceScore: 89,
        },
        {
            year: "1953",
            type: "incident",
            title: "Operation Success Media Blitz",
            summary: "CIA-backed journalists plant disinformation stories in major newspapers to build public support for the Guatemala coup, demonstrating Mockingbird's operational capability.",
            source: "Declassified CIA Files",
            evidenceScore: 95,
        },
        {
            year: "1975",
            type: "leak",
            title: "Church Committee Revelations",
            summary: "Senate Church Committee hearings reveal the CIA had recruited over 400 American journalists. CIA Director William Colby admits agents had posed as reporters domestically and abroad.",
            source: "Senate Church Committee Final Report",
            evidenceScore: 97,
        },
        {
            year: "1977",
            type: "discovery",
            title: "Rolling Stone Investigation",
            summary: "Carl Bernstein publishes a 25,000-word exposé in Rolling Stone naming specific journalists, outlets, and operations. The CIA confirms key details.",
            source: "Rolling Stone, Oct 1977",
            evidenceScore: 95,
        },
        {
            year: "1996",
            type: "government",
            title: "Congress Passes Prohibition",
            summary: "The Intelligence Authorization Act prohibits the CIA from using journalists as paid agents — implicitly acknowledging the practice existed.",
            source: "Intelligence Authorization Act, 1996",
            evidenceScore: 99,
        },
        {
            year: "Today",
            type: "update",
            title: "Ongoing Debate",
            summary: "The full scope of Operation Mockingbird remains classified. Media analysts and press freedom organisations continue to cite it in debates over government-media relationships.",
            evidenceScore: 89,
        },
    ],
};

// Fallback timeline generator from investigation fields
export function getFallbackTimeline(
    year: string | undefined,
    title: string,
    description: string,
    category: string
): TimelineEntry[] {
    const entries: TimelineEntry[] = [];
    if (year) {
        entries.push({
            year,
            type: "incident",
            title: `The ${title} Begins`,
            summary: description,
        });
    }
    entries.push({
        year: "Today",
        type: "update",
        title: "Investigation Ongoing",
        summary: `Research and investigation into ${title} continues. New evidence and witness testimony are regularly reviewed.`,
    });
    return entries;
}
